// Generated by `cargo xtask codegen` from the layout table (`crates/ledger/src/payload.rs`); do not edit.
// The `ICDescriptor` masses `m0 m1 m2` as one ternary colour (debug_tooling_plan §E; render contract Part 5):
// `dbg_ternary`, the masses as linear RGB scaled by `1/max(mᵢ)`, so equal masses draw white and each vertex its primary
// (REQ-TOOL-154). A colour occupant, it reads the masses through `ICDescriptor.m0`, `ICDescriptor.m1` and
// `ICDescriptor.m2`; it certifies the decoder, independent of any integration.
fn colour(ctx: Ctx) -> vec3<f32> {
    return dbg_ternary(vec3<f32>(ctx.ic.m0, ctx.ic.m1, ctx.ic.m2), ctx.frag_xy);
}
