// Generated by `cargo xtask codegen` from the layout table (`crates/ledger/src/payload.rs`); do not edit.
// The 'as direction-cosines' view of the vector field `r_sh` (gui_state_contract §4; dd_generation_root §3.8), beside
// its '‖·‖ as scalar' view, `crates/render/frag/debug/generated/r_sh.wgsl`. A colour occupant, it reads the field
// through `SimState.r_sh` and draws `dbg_dircos6`, render contract Part 5's rendering of its direction cosines
// (REQ-TOOL-157).
fn colour(ctx: Ctx) -> vec3<f32> {
    return dbg_dircos6(ctx.sample.r_sh, ctx.frag_xy);
}
