//! The colour-vision simulation (TASK-M7-20; dd_colouring §3.8; R-78, R-123, R-383, R-386): the pass's WGSL,
//! `shaders/wgsl/compositor/cvd.wgsl`, run on the GPU, and its CPU mirror, `render::display::cvd`, against the golden
//! values in `fixtures/cvd/goldens.json`, generated from the reference implementation R-383 pins (DaltonLens-Python at
//! commit `3cba5e6`, in linear sRGB, through its simulators' linear-RGB path):
//! - REQ-COL-042, dd_colouring unit test 10 (`cvd_simulation_*`): protan, deutan and tritan match the goldens, the
//!   matrices and the simulated colours; achromatopsia yields `R = G = B` exactly; the stage takes linear colour, so a
//!   simulation applied before linearisation is a detectable difference.
//! - REQ-COL-045 (`cvd_modes_*`): the Display window's five modes, and the pass transforming a test colour set under
//!   each, by the mode's uniform: Viénot or Brettel matching the goldens, `M_achrom` grey, off the identity.
//! - REQ-COL-061 (`cvd_hatch_distinct_*`): under each simulation, the hatch stays distinguishable from every palette
//!   entry REQ-COL-055 measured against, by the criterion proposed (R-71; R-386), the distances printed.
//!
//! Each GPU check takes the WGSL as text, so its control runs it on the text with one mutation; each CPU check takes the
//! function or the data it checks, so its control runs it on a wrong one.

use std::path::Path;

use render::display::cvd::{self, CvdMode, CvdPass, Mat3, Matrices};
use render::present::{self, Rgb};
use validation::gpu::{BindingKind, GpuHarness};
use validation::negative_control;

// REQ-COL-055's palette list, the one its collision check in `tests/prelude.rs` measures (R-386).
#[path = "support/palettes.rs"]
mod palettes;
use palettes::hex;

// ── the goldens ─────────────────────────────────────────────────────────────────────────────────────────────────────

/// The golden file, generated by `fixtures/cvd/generate.py` from the pinned reference.
const GOLDENS: &str = "fixtures/cvd/goldens.json";

/// The pinned reference commit (R-383).
const COMMIT: &str = "3cba5e6a7c8f0e8199c8f83f1afb58eb6dab7a3d";

#[derive(serde::Deserialize)]
struct Goldens {
    source: Source,
    matrices: GoldenMatrices,
    colours: Vec<Colour>,
}

#[derive(serde::Deserialize)]
struct Source {
    commit: String,
    path: String,
}

#[derive(serde::Deserialize, Clone, Copy)]
struct GoldenMatrices {
    #[serde(rename = "LMS_from_linearRGB")]
    lms_from_linear_rgb: Mat3,
    #[serde(rename = "linearRGB_from_LMS")]
    linear_rgb_from_lms: Mat3,
    vienot_protan: Mat3,
    vienot_deutan: Mat3,
    brettel_tritan: GoldenBrettel,
}

#[derive(serde::Deserialize, Clone, Copy)]
struct GoldenBrettel {
    #[serde(rename = "H1")]
    h1: Mat3,
    #[serde(rename = "H2")]
    h2: Mat3,
    n_sep_lms: [f64; 3],
    #[serde(rename = "T1")]
    t1: Mat3,
    #[serde(rename = "T2")]
    t2: Mat3,
    n_sep_rgb: [f64; 3],
}

/// One test colour: its 8-bit sRGB, its linear value as the reference decoded it, and the reference's simulations.
#[derive(serde::Deserialize, Clone, Copy, Debug)]
struct Colour {
    srgb8: [u8; 3],
    linear: Rgb,
    protan: Rgb,
    deutan: Rgb,
    tritan: Rgb,
}

impl Colour {
    /// The reference's simulation under `mode`, for the three it computes.
    fn golden(&self, mode: CvdMode) -> Option<Rgb> {
        match mode {
            CvdMode::Protanopia => Some(self.protan),
            CvdMode::Deuteranopia => Some(self.deutan),
            CvdMode::Tritanopia => Some(self.tritan),
            CvdMode::Off | CvdMode::Achromatopsia => None,
        }
    }
}

fn root() -> &'static Path {
    Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/../.."))
}

fn goldens() -> Goldens {
    let path = root().join(GOLDENS);
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("{}: {e}", path.display()))
}

/// The three simulations the reference computes.
const DICHROMACIES: [CvdMode; 3] = [
    CvdMode::Deuteranopia,
    CvdMode::Protanopia,
    CvdMode::Tritanopia,
];

/// The four simulations, every mode but off.
const SIMULATIONS: [CvdMode; 4] = [
    CvdMode::Deuteranopia,
    CvdMode::Protanopia,
    CvdMode::Tritanopia,
    CvdMode::Achromatopsia,
];

/// The f32 unit roundoff, `2⁻²⁴`.
const U: f64 = f32::EPSILON as f64 / 2.0;

/// The f64 roundoff of a matrix entry that is zero in exact arithmetic: the reference's are below `2e-16`.
const NOISE: f64 = 1e-15;

/// The f64 agreement asked of the mirror with the reference: both compute the same products in f64, by different
/// routes (numpy's LAPACK inverse, this crate's adjugate), so they agree to a few f64 roundings of the largest term;
/// `1e-12` relative to the larger of 1 and the value, the inverse's entries reaching 69.
fn close64(a: f64, b: f64) -> bool {
    (a - b).abs() <= 1e-12 * a.abs().max(b.abs()).max(1.0)
}

// ── REQ-COL-042: the matrices and the simulated colours (dd_colouring unit test 10) ────────────────────────────────

fn check_mat(name: &str, got: &Mat3, want: &Mat3) {
    for i in 0..3 {
        for j in 0..3 {
            assert!(
                close64(got[i][j], want[i][j]),
                "{name}[{i}][{j}] is {}, the reference's {}",
                got[i][j],
                want[i][j]
            );
        }
    }
}

fn check_vec(name: &str, got: &[f64; 3], want: &[f64; 3]) {
    check_mat(name, &[*got; 3], &[*want; 3]);
}

/// The matrices derived from dd_colouring §3.8's data are the reference's, at the pinned commit.
fn check_matrices(m: &Matrices) {
    let g = goldens();
    assert_eq!(
        g.source.commit, COMMIT,
        "the goldens are not the pinned commit's"
    );
    assert!(
        g.source.path.starts_with("_simulate_dichromacy_linear_rgb"),
        "the goldens are not from the linear-RGB path: {}",
        g.source.path
    );
    let r = g.matrices;
    check_mat(
        "LMS_from_linearRGB",
        &m.lms_from_linear_rgb,
        &r.lms_from_linear_rgb,
    );
    check_mat(
        "linearRGB_from_LMS",
        &m.linear_rgb_from_lms,
        &r.linear_rgb_from_lms,
    );
    check_mat("Viénot protan", &m.vienot_protan, &r.vienot_protan);
    check_mat("Viénot deutan", &m.vienot_deutan, &r.vienot_deutan);
    let (b, rb) = (&m.brettel_tritan, &r.brettel_tritan);
    check_mat("Brettel tritan H1", &b.h1, &rb.h1);
    check_mat("Brettel tritan H2", &b.h2, &rb.h2);
    check_vec("Brettel tritan n_sep (LMS)", &b.n_sep_lms, &rb.n_sep_lms);
    check_mat("Brettel tritan T1", &b.t1, &rb.t1);
    check_mat("Brettel tritan T2", &b.t2, &rb.t2);
    check_vec("Brettel tritan n_sep (RGB)", &b.n_sep_rgb, &rb.n_sep_rgb);
}

#[test]
fn cvd_simulation_matrices_match_the_reference() {
    check_matrices(&Matrices::derive());
}

negative_control!(
    cvd_simulation_matrices_match_the_reference,
    "an LMS model without the Judd–Vos correction (sRGB's own XYZ matrix) must not pass as the reference's",
    expected = "LMS_from_linearRGB[0][0] is",
    {
        let mut m = Matrices::derive();
        let srgb_xyz = [
            [0.412456, 0.3575761, 0.1804375],
            [0.212672, 0.7151522, 0.0721750],
            [0.019333, 0.1191920, 0.9503041],
        ];
        m.lms_from_linear_rgb = cvd::mul(&cvd::LMS_FROM_XYZ_JUDD_VOS, &srgb_xyz);
        check_matrices(&m)
    }
);

/// `simulate` (the mirror) gives each test colour the reference's protan, deutan and tritan, in f64.
fn check_mirror(simulate: fn(CvdMode, Rgb) -> Rgb) {
    for c in goldens().colours {
        for mode in DICHROMACIES {
            let (got, want) = (simulate(mode, c.linear), c.golden(mode).unwrap());
            assert!(
                (0..3).all(|k| close64(got[k], want[k])),
                "{} of {:?} is {got:?}, the reference's {want:?}",
                mode.label(),
                c.srgb8
            );
        }
    }
}

#[test]
fn cvd_simulation_mirror_matches_the_reference_goldens() {
    check_mirror(cvd::simulate);
}

negative_control!(
    cvd_simulation_mirror_matches_the_reference_goldens,
    "a tritan that always takes the first half-plane, Brettel's selection dropped, must fail",
    expected = "tritanopia of",
    check_mirror(|mode, c| match mode {
        CvdMode::Tritanopia => cvd::apply(&Matrices::get().brettel_tritan.t1, c),
        _ => cvd::simulate(mode, c),
    })
);

// ── the WGSL on the GPU ─────────────────────────────────────────────────────────────────────────────────────────────

/// The test entry appended to the pass's WGSL: pixel `k` of a `WIDTH`-wide target evaluates `cvd_sim` on case `k`,
/// whose x, y, z are the colour's f32 bits and w the mode's code, and returns the result's bits.
const ENTRY: &str = r"
@group(1) @binding(0) var<storage, read> cvd_cases: array<vec4<u32>>;

@fragment
fn t_cvd(@builtin(position) pos: vec4<f32>) -> @location(0) vec4<u32> {
    let v = cvd_cases[u32(pos.y) * 64u + u32(pos.x)];
    return vec4<u32>(bitcast<vec3<u32>>(cvd_sim(v.w, bitcast<vec3<f32>>(v.xyz))), 0u);
}
";

/// The test entry's target width, in cases per row.
const WIDTH: usize = 64;

/// The pass's WGSL, with at most one mutation, a control's: `from` replaced by `to`, which the text must contain.
#[derive(Clone, Copy, Debug)]
struct Text {
    from: &'static str,
    to: &'static str,
}

const AS_IS: Text = Text { from: "", to: "" };

#[cfg(feature = "controls")]
fn mutated(from: &'static str, to: &'static str) -> Text {
    assert!(
        cvd::CVD_WGSL.contains(from),
        "the WGSL has no `{from}` to mutate"
    );
    Text { from, to }
}

impl Text {
    fn source(self) -> String {
        if self.from.is_empty() {
            cvd::CVD_WGSL.to_string()
        } else {
            cvd::CVD_WGSL.replacen(self.from, self.to, 1)
        }
    }
}

fn gpu() -> GpuHarness {
    GpuHarness::new().expect("a GPU device")
}

/// `cvd_sim(mode, c)` on the GPU for each `(mode, c)`, in f64.
fn run_sim(gpu: &GpuHarness, text: Text, cases: &[(CvdMode, Rgb)]) -> Vec<Rgb> {
    let module = format!("{}\n{ENTRY}", text.source());
    let rows = cases.len().div_ceil(WIDTH);
    let mut words = vec![0u32; rows * WIDTH * 4];
    for (k, (mode, c)) in cases.iter().enumerate() {
        for j in 0..3 {
            words[4 * k + j] = (c[j] as f32).to_bits();
        }
        words[4 * k + 3] = mode.code();
    }
    let kernel = gpu
        .fragment(
            &module,
            "t_cvd",
            &[&[], &[BindingKind::Storage]],
            WIDTH as u32,
            rows as u32,
        )
        .unwrap_or_else(|e| panic!("{e:?}"));
    let out = kernel
        .draw(&[&[], &[&words]])
        .unwrap_or_else(|e| panic!("{e:?}"));
    out[..cases.len()]
        .iter()
        .map(|p| [0, 1, 2].map(|j| f64::from(f32::from_bits(p[j]))))
        .collect()
}

/// The worst-case f32 error of `m · c` against the f64 product: the colour's and the matrix's roundings to f32 and the
/// three products and two sums, `5U` relative each at most, so `8U · Σⱼ |mᵢⱼ| |cⱼ|` with room; for Brettel, the larger
/// of its two transforms', which agree on the separating plane, so a colour near it may take either. A simulation adds
/// [`NOISE`]` · Σⱼ |cⱼ|` for the entries that are zero in exact arithmetic (Viénot's third column above its diagonal,
/// blue being on the plane), which the reference holds as f64 roundoff and the mirror computes by another route.
fn bound(mode: CvdMode, c: Rgb) -> Rgb {
    let m = Matrices::get();
    let row = |mat: &Mat3, i: usize| (0..3).map(|j| mat[i][j].abs() * c[j].abs()).sum::<f64>();
    std::array::from_fn(|i| {
        8.0 * U
            * match mode {
                CvdMode::Off => 0.0,
                CvdMode::Deuteranopia => row(&m.vienot_deutan, i),
                CvdMode::Protanopia => row(&m.vienot_protan, i),
                CvdMode::Tritanopia => {
                    row(&m.brettel_tritan.t1, i).max(row(&m.brettel_tritan.t2, i))
                }
                CvdMode::Achromatopsia => row(&[cvd::ACHROM_ROW; 3], i),
            }
            + match mode {
                CvdMode::Off => 0.0,
                _ => NOISE * (c[0].abs() + c[1].abs() + c[2].abs()),
            }
    })
}

/// `cvd_sim` on the GPU gives each test colour the reference's protan, deutan and tritan, within the f32 bound.
fn check_gpu_goldens(gpu: &GpuHarness, text: Text) {
    let colours = goldens().colours;
    let cases: Vec<(CvdMode, Rgb)> = DICHROMACIES
        .iter()
        .flat_map(|&m| colours.iter().map(move |c| (m, c.linear)))
        .collect();
    let got = run_sim(gpu, text, &cases);
    for (k, &(mode, c)) in cases.iter().enumerate() {
        let want = colours[k % colours.len()].golden(mode).unwrap();
        let b = bound(mode, c);
        assert!(
            (0..3).all(|j| (got[k][j] - want[j]).abs() <= b[j]),
            "the GPU's {} of {:?} is {:?}, the reference's {want:?}, beyond {b:?}",
            mode.label(),
            colours[k % colours.len()].srgb8,
            got[k]
        );
    }
}

#[test]
fn cvd_simulation_gpu_matches_the_reference_goldens() {
    check_gpu_goldens(&gpu(), AS_IS);
}

negative_control!(
    cvd_simulation_gpu_matches_the_reference_goldens,
    "a tritan whose half-planes are swapped must fail",
    expected = "the GPU's tritanopia of",
    check_gpu_goldens(
        &gpu(),
        mutated(
            "dot(c, CVD_BRETTEL_TRITAN_SEP) < 0.0",
            "dot(c, CVD_BRETTEL_TRITAN_SEP) > 0.0"
        )
    )
);

/// Colours beyond the goldens' lattice for the achromatopsia check: a 17-step lattice, every 8-bit grey's neighbours
/// included.
fn lattice17() -> Vec<Rgb> {
    let s = |k: usize| present::srgb_to_linear(k as f64 / 16.0);
    (0..17 * 17 * 17)
        .map(|k| [s(k / 289), s(k / 17 % 17), s(k % 17)])
        .collect()
}

/// Achromatopsia yields `R = G = B` exactly, on the GPU and in the mirror, and the grey is `M_achrom`'s, within the
/// f32 bound on the GPU.
fn check_achrom(gpu: &GpuHarness, text: Text) {
    let colours: Vec<Rgb> = goldens()
        .colours
        .iter()
        .map(|c| c.linear)
        .chain(lattice17())
        .collect();
    let cases: Vec<(CvdMode, Rgb)> = colours
        .iter()
        .map(|&c| (CvdMode::Achromatopsia, c))
        .collect();
    let got = run_sim(gpu, text, &cases);
    for (c, g) in colours.iter().zip(&got) {
        let want =
            cvd::ACHROM_ROW[0] * c[0] + cvd::ACHROM_ROW[1] * c[1] + cvd::ACHROM_ROW[2] * c[2];
        let cpu = cvd::simulate(CvdMode::Achromatopsia, *c);
        assert!(
            g[0].to_bits() == g[1].to_bits() && g[1].to_bits() == g[2].to_bits(),
            "the GPU's achromatopsia of {c:?} is {g:?}, not R = G = B"
        );
        assert!(
            cpu[0].to_bits() == cpu[1].to_bits() && cpu[1].to_bits() == cpu[2].to_bits(),
            "the mirror's achromatopsia of {c:?} is {cpu:?}, not R = G = B"
        );
        assert!(
            (g[0] - want).abs() <= bound(CvdMode::Achromatopsia, *c)[0] && close64(cpu[0], want),
            "achromatopsia of {c:?} is {g:?} on the GPU and {cpu:?} in the mirror, not M_achrom's {want}"
        );
    }
}

#[test]
fn cvd_simulation_achrom_is_grey_exactly() {
    check_achrom(&gpu(), AS_IS);
}

negative_control!(
    cvd_simulation_achrom_is_grey_exactly,
    "an achromatopsia that keeps a thousandth of the colour must fail",
    expected = "not R = G = B",
    check_achrom(
        &gpu(),
        mutated(
            "return vec3<f32>(dot(c, CVD_ACHROM_ROW));",
            "return mix(c, vec3<f32>(dot(c, CVD_ACHROM_ROW)), 0.999);"
        )
    )
);

// ── the stage: the pass on linear colour, 8-bit sRGB in and out ─────────────────────────────────────────────────────

/// Where the pass is put: after linearisation, as the stage is, or before it, the layer's 8-bit sRGB read and written
/// as they are stored, through non-sRGB views of the same textures.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Placement {
    Linear,
    PreLinearisation,
}

/// The pass drawn on a layer holding `colours` (8-bit sRGB, one per pixel), under `mode`, placed as `placement`
/// says; the screen's 8-bit sRGB, pixel by pixel.
fn run_stage(
    gpu: &GpuHarness,
    colours: &[[u8; 3]],
    mode: CvdMode,
    placement: Placement,
) -> Vec<[u8; 3]> {
    use wgpu::util::DeviceExt;
    let (device, queue) = (gpu.device(), gpu.queue());
    let width = colours.len() as u32;
    let srgb = wgpu::TextureFormat::Rgba8UnormSrgb;
    let unorm = wgpu::TextureFormat::Rgba8Unorm;
    let view_format = match placement {
        Placement::Linear => srgb,
        Placement::PreLinearisation => unorm,
    };
    let size = wgpu::Extent3d {
        width,
        height: 1,
        depth_or_array_layers: 1,
    };
    let texels: Vec<u8> = colours
        .iter()
        .flat_map(|c| [c[0], c[1], c[2], 255])
        .collect();
    let source = device.create_texture_with_data(
        queue,
        &wgpu::TextureDescriptor {
            label: Some("layer"),
            size,
            mip_level_count: 1,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format: srgb,
            usage: wgpu::TextureUsages::TEXTURE_BINDING,
            view_formats: &[unorm],
        },
        wgpu::util::TextureDataOrder::LayerMajor,
        &texels,
    );
    let screen = device.create_texture(&wgpu::TextureDescriptor {
        label: Some("screen"),
        size,
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: srgb,
        usage: wgpu::TextureUsages::RENDER_ATTACHMENT | wgpu::TextureUsages::COPY_SRC,
        view_formats: &[unorm],
    });
    let view = |t: &wgpu::Texture| {
        t.create_view(&wgpu::TextureViewDescriptor {
            format: Some(view_format),
            ..Default::default()
        })
    };
    let pass = CvdPass::new(device, view_format).unwrap_or_else(|e| panic!("{e}"));
    let row = (4 * width).next_multiple_of(256);
    let staging = device.create_buffer(&wgpu::BufferDescriptor {
        label: Some("screen readback"),
        size: u64::from(row),
        usage: wgpu::BufferUsages::COPY_DST | wgpu::BufferUsages::MAP_READ,
        mapped_at_creation: false,
    });
    let mut encoder = device.create_command_encoder(&Default::default());
    pass.draw(device, &mut encoder, &view(&source), &view(&screen), mode);
    encoder.copy_texture_to_buffer(
        screen.as_image_copy(),
        wgpu::TexelCopyBufferInfo {
            buffer: &staging,
            layout: wgpu::TexelCopyBufferLayout {
                offset: 0,
                bytes_per_row: Some(row),
                rows_per_image: None,
            },
        },
        size,
    );
    queue.submit([encoder.finish()]);
    let slice = staging.slice(..);
    slice.map_async(wgpu::MapMode::Read, |r| r.expect("the readback maps"));
    device
        .poll(wgpu::PollType::wait_indefinitely())
        .expect("the device polls");
    let bytes = slice
        .get_mapped_range()
        .expect("the readback maps")
        .to_vec();
    (0..colours.len())
        .map(|k| [bytes[4 * k], bytes[4 * k + 1], bytes[4 * k + 2]])
        .collect()
}

/// The screen's expected 8-bit sRGB for a simulated linear colour: clamped to [0, 1], encoded by dd_colouring §3.1's
/// transfer, rounded.
fn encode8(c: Rgb) -> [u8; 3] {
    c.map(|x| (present::linear_to_srgb(x.clamp(0.0, 1.0)) * 255.0).round() as u8)
}

/// The stage's expected screen for each test colour under `mode`: the reference's golden for the three it computes,
/// `M_achrom`'s grey, the colour itself for off.
fn expected8(c: &Colour, mode: CvdMode) -> [u8; 3] {
    match mode {
        CvdMode::Off => c.srgb8,
        CvdMode::Achromatopsia => encode8(cvd::simulate(mode, c.linear)),
        _ => encode8(c.golden(mode).unwrap()),
    }
}

/// The test colours the pass, placed as `placement` says, draws more than one 8-bit step from the expected screen
/// under `mode` (the GPU's f32 and its sRGB encode's rounding are within one).
fn stage_misses(gpu: &GpuHarness, mode: CvdMode, placement: Placement) -> Vec<String> {
    let colours = goldens().colours;
    let input: Vec<[u8; 3]> = colours.iter().map(|c| c.srgb8).collect();
    let got = run_stage(gpu, &input, mode, placement);
    colours
        .iter()
        .zip(&got)
        .filter_map(|(c, g)| {
            let want = expected8(c, mode);
            let off = (0..3)
                .map(|j| (i32::from(g[j]) - i32::from(want[j])).abs())
                .max()
                .unwrap();
            (off > 1).then(|| format!("{:?} → {g:?}, expected {want:?}", c.srgb8))
        })
        .collect()
}

/// The stage, placed as `placement` says, draws every test colour's expected screen under every mode.
fn check_stage(gpu: &GpuHarness, placement: Placement) {
    for mode in CvdMode::ALL {
        let misses = stage_misses(gpu, mode, placement);
        assert!(
            misses.is_empty(),
            "the stage ({placement:?}) misses the reference under {} on {} colours: {:?}",
            mode.label(),
            misses.len(),
            &misses[..misses.len().min(4)]
        );
    }
}

/// Every simulation applied before linearisation misses the reference on some test colour, by more than the stage's
/// one-step tolerance: the check above detects a misplaced stage.
fn check_prelinearisation_detected(gpu: &GpuHarness, placement: Placement) {
    for mode in SIMULATIONS {
        let misses = stage_misses(gpu, mode, placement);
        eprintln!(
            "{} applied {placement:?}: {} of the test colours miss the reference",
            mode.label(),
            misses.len()
        );
        assert!(
            !misses.is_empty(),
            "{} applied {placement:?} is not told from the stage on linear colour",
            mode.label()
        );
    }
}

#[test]
fn cvd_simulation_stage_takes_linear_colour() {
    check_stage(&gpu(), Placement::Linear);
}

negative_control!(
    cvd_simulation_stage_takes_linear_colour,
    "the pass applied before linearisation must miss the reference",
    expected = "the stage (PreLinearisation) misses the reference under deuteranopia",
    check_stage(&gpu(), Placement::PreLinearisation)
);

#[test]
fn cvd_simulation_prelinearisation_is_detected() {
    check_prelinearisation_detected(&gpu(), Placement::PreLinearisation);
}

negative_control!(
    cvd_simulation_prelinearisation_is_detected,
    "the stage on linear colour is not a misplaced one",
    expected = "deuteranopia applied Linear is not told from the stage on linear colour",
    check_prelinearisation_detected(&gpu(), Placement::Linear)
);

// ── REQ-COL-045: the five modes ─────────────────────────────────────────────────────────────────────────────────────

/// The Display window's modes, in its order (render_gui_spec § "Display — the last stages"; R-123).
const DISPLAY_WINDOW: [&str; 5] = [
    "off",
    "deuteranopia",
    "protanopia",
    "tritanopia",
    "achromatopsia",
];

fn check_modes(modes: &[CvdMode]) {
    let labels: Vec<&str> = modes.iter().map(|m| m.label()).collect();
    assert_eq!(
        labels, DISPLAY_WINDOW,
        "the modes are not the Display window's"
    );
    let codes: Vec<u32> = modes.iter().map(|m| m.code()).collect();
    assert_eq!(
        codes,
        [0, 1, 2, 3, 4],
        "the modes' codes are not the WGSL's"
    );
}

#[test]
fn cvd_modes_are_the_display_windows_five() {
    check_modes(&CvdMode::ALL);
}

negative_control!(
    cvd_modes_are_the_display_windows_five,
    "the four modes before R-123 added achromatopsia must fail",
    expected = "the modes are not the Display window's",
    check_modes(&CvdMode::ALL[..4])
);

/// The pass, drawn on a float layer of the test colours (linear, as the reference decoded them) into a float screen,
/// under each mode by its uniform: within the f32 bound of `expect(mode, colour)`, clamped to [0, 1] as the pass
/// clamps; off exactly the colour; achromatopsia `R = G = B` exactly.
fn check_pass_modes(gpu: &GpuHarness, expect: fn(&Colour, CvdMode) -> Rgb) {
    let colours = goldens().colours;
    for mode in CvdMode::ALL {
        let got = run_float_stage(gpu, &colours, mode);
        for (c, g) in colours.iter().zip(&got) {
            let want = expect(c, mode).map(|x| x.clamp(0.0, 1.0));
            let b = bound(mode, c.linear);
            assert!(
                (0..3).all(|j| (g[j] - want[j]).abs() <= b[j]),
                "the pass's {} of {:?} is {g:?}, not {want:?}",
                mode.label(),
                c.srgb8
            );
            if mode == CvdMode::Achromatopsia {
                assert!(
                    g[0] == g[1] && g[1] == g[2],
                    "the pass's achromatopsia of {:?} is {g:?}",
                    c.srgb8
                );
            }
        }
    }
}

/// What each mode should make of a test colour: the reference's golden, `M_achrom`'s grey (the mirror, checked
/// against the row above), or the colour (off), with each colour rounded to f32 as the float layer holds it.
fn expected(c: &Colour, mode: CvdMode) -> Rgb {
    match mode {
        CvdMode::Off => c.linear.map(|x| f64::from(x as f32)),
        CvdMode::Achromatopsia => cvd::simulate(mode, c.linear),
        _ => c.golden(mode).unwrap(),
    }
}

/// The pass on an `Rgba32Float` layer of `colours`' linear values into an `Rgba32Float` screen, under `mode`.
fn run_float_stage(gpu: &GpuHarness, colours: &[Colour], mode: CvdMode) -> Vec<Rgb> {
    use wgpu::util::DeviceExt;
    let (device, queue) = (gpu.device(), gpu.queue());
    let format = wgpu::TextureFormat::Rgba32Float;
    let size = wgpu::Extent3d {
        width: colours.len() as u32,
        height: 1,
        depth_or_array_layers: 1,
    };
    let texels: Vec<u8> = colours
        .iter()
        .flat_map(|c| {
            [
                c.linear[0] as f32,
                c.linear[1] as f32,
                c.linear[2] as f32,
                1.0,
            ]
        })
        .flat_map(f32::to_le_bytes)
        .collect();
    let descriptor = |label, usage| wgpu::TextureDescriptor {
        label: Some(label),
        size,
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format,
        usage,
        view_formats: &[],
    };
    let source = device.create_texture_with_data(
        queue,
        &descriptor("layer", wgpu::TextureUsages::TEXTURE_BINDING),
        wgpu::util::TextureDataOrder::LayerMajor,
        &texels,
    );
    let screen = device.create_texture(&descriptor(
        "screen",
        wgpu::TextureUsages::RENDER_ATTACHMENT | wgpu::TextureUsages::COPY_SRC,
    ));
    let row = (16 * colours.len() as u32).next_multiple_of(256);
    let staging = device.create_buffer(&wgpu::BufferDescriptor {
        label: Some("screen readback"),
        size: u64::from(row),
        usage: wgpu::BufferUsages::COPY_DST | wgpu::BufferUsages::MAP_READ,
        mapped_at_creation: false,
    });
    let pass = CvdPass::new(device, format).unwrap_or_else(|e| panic!("{e}"));
    let mut encoder = device.create_command_encoder(&Default::default());
    pass.draw(
        device,
        &mut encoder,
        &source.create_view(&Default::default()),
        &screen.create_view(&Default::default()),
        mode,
    );
    encoder.copy_texture_to_buffer(
        screen.as_image_copy(),
        wgpu::TexelCopyBufferInfo {
            buffer: &staging,
            layout: wgpu::TexelCopyBufferLayout {
                offset: 0,
                bytes_per_row: Some(row),
                rows_per_image: None,
            },
        },
        size,
    );
    queue.submit([encoder.finish()]);
    let slice = staging.slice(..);
    slice.map_async(wgpu::MapMode::Read, |r| r.expect("the readback maps"));
    device
        .poll(wgpu::PollType::wait_indefinitely())
        .expect("the device polls");
    let bytes = slice
        .get_mapped_range()
        .expect("the readback maps")
        .to_vec();
    let f = |k: usize| {
        f64::from(f32::from_le_bytes([
            bytes[k],
            bytes[k + 1],
            bytes[k + 2],
            bytes[k + 3],
        ]))
    };
    (0..colours.len())
        .map(|k| [f(16 * k), f(16 * k + 4), f(16 * k + 8)])
        .collect()
}

#[test]
fn cvd_modes_transform_the_test_colours() {
    check_pass_modes(&gpu(), expected);
}

negative_control!(
    cvd_modes_transform_the_test_colours,
    "deuteranopia expected where protanopia is asked, the two modes' codes crossed, must fail",
    expected = "the pass's deuteranopia of",
    check_pass_modes(&gpu(), |c, mode| match mode {
        CvdMode::Deuteranopia => c.protan,
        _ => expected(c, mode),
    })
);

/// The mirror's off is the identity, bit for bit, on every test colour and the 17-step lattice.
fn check_off(simulate: fn(CvdMode, Rgb) -> Rgb) {
    for c in goldens()
        .colours
        .iter()
        .map(|c| c.linear)
        .chain(lattice17())
    {
        let got = simulate(CvdMode::Off, c);
        assert!(
            (0..3).all(|j| got[j].to_bits() == c[j].to_bits()),
            "off changes {c:?} to {got:?}"
        );
    }
}

#[test]
fn cvd_modes_off_is_the_identity() {
    check_off(cvd::simulate);
}

negative_control!(
    cvd_modes_off_is_the_identity,
    "an off that rounds the colour through f32 must fail",
    expected = "off changes",
    check_off(|mode, c| match mode {
        CvdMode::Off => c.map(|x| f64::from(x as f32)),
        _ => cvd::simulate(mode, c),
    })
);

// ── REQ-COL-061: the hatch under each simulation (R-386; R-71, proposed) ───────────────────────────────────────────

/// The OKLab distance between two linear colours.
fn oklab_distance(a: Rgb, b: Rgb) -> f64 {
    let (p, q) = (present::linear_to_oklab(a), present::linear_to_oklab(b));
    ((p[0] - q[0]).powi(2) + (p[1] - q[1]).powi(2) + (p[2] - q[2]).powi(2)).sqrt()
}

/// What the screen shows of the linear colour `c` under `mode`: simulated, then clamped to [0, 1], as the pass writes.
fn seen(mode: CvdMode, c: Rgb) -> Rgb {
    cvd::simulate(mode, c).map(|x| x.clamp(0.0, 1.0))
}

/// REQ-COL-061's threshold (proposed, R-71; R-386): the OKLab distance from R-16's flat magenta `#FF00FF` to body-1
/// escape's `#E034C6`, 0.101, the distance R-132 ruled a collision and REQ-COL-055's bound, taken unsimulated.
fn tau() -> f64 {
    oklab_distance(hex(0xFF00FF), hex(0xE034C6))
}

/// The hatch as seen under one mode: each stripe colour's least OKLab distance to a palette entry and that entry's
/// name, both simulated, and the two simulated stripes' distance from each other, the pattern's contrast.
struct Seen {
    nearest: [(f64, String); 2],
    stripes: f64,
}

fn measure(mode: CvdMode, hatch: [Rgb; 2], entries: &[(String, Rgb)]) -> Seen {
    let labs: Vec<Rgb> = entries
        .iter()
        .map(|(_, p)| present::linear_to_oklab(seen(mode, *p)))
        .collect();
    let nearest = hatch.map(|h| {
        let q = present::linear_to_oklab(seen(mode, h));
        labs.iter()
            .zip(entries)
            .map(|(p, (name, _))| {
                let d =
                    ((p[0] - q[0]).powi(2) + (p[1] - q[1]).powi(2) + (p[2] - q[2]).powi(2)).sqrt();
                (d, name.clone())
            })
            .fold((f64::INFINITY, String::new()), |a, b| {
                if b.0 < a.0 {
                    b
                } else {
                    a
                }
            })
    });
    Seen {
        nearest,
        stripes: oklab_distance(seen(mode, hatch[0]), seen(mode, hatch[1])),
    }
}

/// REQ-COL-061's criterion (proposed, R-71; R-386), under each simulation: the hatch is distinguishable from the
/// palette if each stripe colour is farther than [`tau`] from every palette entry, both simulated; and where a stripe
/// colour falls within it, the pattern counts: the hatch is still distinguishable if its two stripes, simulated, are
/// farther than [`tau`] apart, since it then shows as diagonal stripes, which no palette entry draws, each drawing one
/// flat colour. Under achromatopsia every stripe colour falls within it (the grey ramp), and the pattern's contrast is
/// its lightness step under `M_achrom`. Each mode's distances are printed, the proposal's evidence.
fn check_hatch_distinct(colours: [[u8; 3]; 2]) {
    let entries = palettes::entries();
    let hatch = colours.map(present::srgb8);
    let tau = tau();
    let hexes = colours.map(|c| format!("#{:02X}{:02X}{:02X}", c[0], c[1], c[2]));
    eprintln!("REQ-COL-061: threshold {tau:.4}, #FF00FF from #E034C6 (R-132's collision)");
    for mode in SIMULATIONS {
        let m = measure(mode, hatch, &entries);
        let clear = m.nearest.iter().all(|(d, _)| *d > tau);
        let pattern = m.stripes > tau;
        eprintln!(
            "{}: {} {:.4} from {}; {} {:.4} from {}; stripes {:.4} apart; {}",
            mode.label(),
            hexes[0],
            m.nearest[0].0,
            m.nearest[0].1,
            hexes[1],
            m.nearest[1].0,
            m.nearest[1].1,
            m.stripes,
            match (clear, pattern) {
                (true, _) => "distinct by colour",
                (false, true) => "distinct by its pattern",
                (false, false) => "NOT distinct",
            }
        );
        assert!(
            clear || pattern,
            "the hatch {} / {} is not distinguishable under {}: {:.4} from {} and {:.4} from {}, its stripes {:.4} \
             apart, the threshold {tau:.4}",
            hexes[0],
            hexes[1],
            mode.label(),
            m.nearest[0].0,
            m.nearest[0].1,
            m.nearest[1].0,
            m.nearest[1].1,
            m.stripes
        );
    }
}

#[test]
fn cvd_hatch_distinct_under_each_simulation() {
    check_hatch_distinct(ledger::gen::prelude::hatch().colours);
}

negative_control!(
    cvd_hatch_distinct_under_each_simulation,
    "a hatch of R-16's flat magenta, one colour, must not be distinguishable",
    expected = "is not distinguishable under",
    check_hatch_distinct([[0xFF, 0x00, 0xFF], [0xFF, 0x00, 0xFF]])
);
