//! The CPU mirror of the shared prelude (`shaders/wgsl/lib/prelude.wgsl`, generated by `ledger::gen::prelude`) and of
//! the presentation layer (`shaders/wgsl/lib/present.wgsl`, hand-written; render contract Part 5, "Presentation
//! layer"), for the assertions that compare the shaders with it. Each function computes, in f64, what its WGSL
//! namesake computes in f32, from the same definitions (render contract Part 5's renderings, R-72; render_gui_spec
//! §10.1; dd_colouring §3.1, §3.7): the arithmetic is written here again, not shared, so a slip in either shows as a
//! disagreement. The colour-space maps are [`crate::colour::space`]'s, the one Rust source of dd_colouring §3.1's
//! transforms, in f64. The data the shaders embed, the published LUT stops (R-122) and the proposed hatch
//! (REQ-COL-055), is read from the ledger that generates them. Colours are linear RGB unless a name says sRGB.

use ledger::gen::prelude;

use crate::colour::space;

/// An RGB triple.
pub type Rgb = [f64; 3];

/// The sRGB transfer, encoded to linear (dd_colouring §3.1), in f64: [`space::srgb_to_linear`].
pub fn srgb_to_linear(c: f64) -> f64 {
    space::srgb_to_linear(c)
}

/// The sRGB transfer's inverse, linear to encoded (dd_colouring §3.1), in f64: [`space::linear_to_srgb`].
pub fn linear_to_srgb(c: f64) -> f64 {
    space::linear_to_srgb(c)
}

/// [`srgb_to_linear`] on each channel.
pub fn srgb_to_linear3(c: Rgb) -> Rgb {
    c.map(srgb_to_linear)
}

/// An 8-bit sRGB colour, decoded to linear.
pub fn srgb8(c: [u8; 3]) -> Rgb {
    c.map(|x| srgb_to_linear(f64::from(x) / 255.0))
}

/// dd_colouring §3.1's `M₁⁻¹`: LMS to linear sRGB ([`space::OKLAB`]'s).
pub const LMS_TO_LINEAR: [[f64; 3]; 3] = space::OKLAB.m1_inv;

/// OKLab to linear sRGB (dd_colouring §3.1), in f64: [`space::oklab_to_linear`].
pub fn oklab_to_linear(lab: Rgb) -> Rgb {
    space::oklab_to_linear(lab)
}

/// Linear sRGB to OKLab (dd_colouring §3.1), in f64, for distances between colours: [`space::linear_to_oklab`].
pub fn linear_to_oklab(rgb: Rgb) -> Rgb {
    space::linear_to_oklab(rgb)
}

/// OKLCH to linear sRGB, the hue `turns` in turns: [`space::oklch_to_oklab`] at `2π · turns` radians, then
/// [`oklab_to_linear`].
pub fn oklch_to_linear(l: f64, c: f64, turns: f64) -> Rgb {
    oklab_to_linear(space::oklch_to_oklab([l, c, std::f64::consts::TAU * turns]))
}

/// `range_norm(x, lo, hi, auto_range, meas)` (render_gui_spec §10.1): `clamp((x − l)/(h − l), 0, 1)` with `(l, h)` the
/// measured `meas` when `auto_range`, else `(lo, hi)`; 0 for a degenerate range, `h = l` (R-72).
pub fn range_norm(x: f64, lo: f64, hi: f64, auto_range: bool, meas: [f64; 2]) -> f64 {
    let (l, h) = if auto_range {
        (meas[0], meas[1])
    } else {
        (lo, hi)
    };
    if h == l {
        0.0
    } else {
        ((x - l) / (h - l)).clamp(0.0, 1.0)
    }
}

/// A LUT ramp over `stops` (sRGB-encoded) at `t`: `t` clamped to [0, 1], the stops at `k/(N − 1)`, interpolated
/// linearly in sRGB, then decoded to linear RGB.
pub fn ramp(stops: &[Rgb], t: f64) -> Rgb {
    let last = stops.len() - 1;
    let x = t.clamp(0.0, 1.0) * last as f64;
    let k = (x.floor() as usize).min(last - 1);
    let f = x - k as f64;
    let (a, b) = (stops[k], stops[k + 1]);
    srgb_to_linear3([0, 1, 2].map(|c| a[c] + (b[c] - a[c]) * f))
}

/// The published viridis stops (R-122), from the ledger's data file.
pub fn viridis_stops() -> Vec<Rgb> {
    prelude::luts()[0].stops()
}

/// The published twilight stops (R-122), from the ledger's data file.
pub fn twilight_stops() -> Vec<Rgb> {
    prelude::luts()[1].stops()
}

/// `ramp_viridis(t)`.
pub fn ramp_viridis(t: f64) -> Rgb {
    ramp(&viridis_stops(), t)
}

/// `ramp_twilight(t)`.
pub fn ramp_twilight(t: f64) -> Rgb {
    ramp(&twilight_stops(), t)
}

/// `ramp_grey(t)`: OKLab `(t, 0, 0)`, `t` clamped to [0, 1].
pub fn ramp_grey(t: f64) -> Rgb {
    oklab_to_linear([t.clamp(0.0, 1.0), 0.0, 0.0])
}

/// `hue_wheel(t)`: OKLCH at the ledger's `(L, C)`, hue `t` turns.
pub fn hue_wheel(t: f64) -> Rgb {
    let (l, c) = prelude::hue_wheel_lc();
    oklch_to_linear(l, c, t)
}

/// Which of the hatch's two colours `debug_invalid` draws at the pixel `frag_xy`: stripe `⌊(⌊x⌋ + ⌊y⌋) / w⌋ mod 2`,
/// `w` the stripe width.
pub fn hatch_stripe(frag_xy: [f64; 2]) -> usize {
    let w = i64::from(prelude::hatch().half_period);
    let s = frag_xy[0].floor() as i64 + frag_xy[1].floor() as i64;
    s.div_euclid(w).rem_euclid(2) as usize
}

/// `debug_invalid(frag_xy)`: the proposed hatch's colour at the pixel (REQ-COL-055; R-132, R-136).
pub fn debug_invalid(frag_xy: [f64; 2]) -> Rgb {
    srgb8(prelude::hatch().colours[hatch_stripe(frag_xy)])
}

/// The neutral "not yet" grey of running samples (R-96; colour_composition §1.4), which a field view draws `d_min`'s
/// unset value in (R-280), as 8-bit sRGB: `#4E4E4E`, OKLab lightness 0.424. Proposed, R-71 (REQ-COL-053, RQ-233):
/// among the 8-bit greys it is the one farthest in OKLab from its nearest outcome class or hatch colour: 0.230 from
/// `#3462E0` (collision 1–2) and 0.231 from `#141418` (bounded), and 0.101 from the viridis ramp; the evidence is
/// `render/tests/not_yet_grey.rs`'s. The human confirms it at the M1 gate. `present.wgsl`'s `DBG_NOT_YET` is its
/// linear value.
pub const NOT_YET_SRGB8: [u8; 3] = [0x4e, 0x4e, 0x4e];

/// `DBG_NOT_YET`: [`NOT_YET_SRGB8`], decoded to linear.
pub fn not_yet() -> Rgb {
    srgb8(NOT_YET_SRGB8)
}

/// The canonical quiet NaN's bits (lowering Part 3a), the absence sentinel.
pub const ABSENT_NAN_BITS: u32 = 0x7fc0_0000;

/// The Okabe–Ito palette (Okabe & Ito 2002), 8-bit sRGB, in its published order.
pub const OKABE_ITO: [[u8; 3]; 8] = [
    [0, 0, 0],
    [230, 159, 0],
    [86, 180, 233],
    [0, 158, 115],
    [240, 228, 66],
    [0, 114, 178],
    [213, 94, 0],
    [204, 121, 167],
];

/// The golden-angle hue of class `i`, in turns: `frac(i · φ_g)`, `φ_g = (√5 − 1)/2` (dd_colouring §3.7).
pub fn golden_turns(i: u32) -> f64 {
    let phi = (5f64.sqrt() - 1.0) / 2.0;
    (f64::from(i) * phi).fract()
}

/// `dbg_cat(i, n)`: Okabe–Ito, cycling, for `n ≤ 8`; the golden angle on `hue_wheel` for every class when `n > 8`.
pub fn dbg_cat(i: u32, n: u32) -> Rgb {
    if n <= 8 {
        srgb8(OKABE_ITO[(i % 8) as usize])
    } else {
        hue_wheel(golden_turns(i))
    }
}

/// `dbg_lin(x, lo, hi)`: `x` on the fixed range, clamped, on the viridis ramp.
pub fn dbg_lin(x: f64, lo: f64, hi: f64) -> Rgb {
    ramp_viridis(range_norm(x, lo, hi, false, [0.0, 0.0]))
}

/// `dbg_log`'s place on the ramp: `1 − 1/(1 + ln(1 + |x|/eps))`.
pub fn dbg_log_t(x: f64, eps: f64) -> f64 {
    1.0 - 1.0 / (1.0 + (1.0 + x.abs() / eps).ln())
}

/// `dbg_log(x, eps)`.
pub fn dbg_log(x: f64, eps: f64) -> Rgb {
    ramp_viridis(dbg_log_t(x, eps))
}

/// `dbg_flag(b)`: Okabe–Ito's bluish green for true, vermillion for false.
pub fn dbg_flag(b: bool) -> Rgb {
    srgb8(if b { OKABE_ITO[3] } else { OKABE_ITO[6] })
}

/// The PCG hash (Jarzynski and Olano 2020, `pcg_hash`).
pub fn pcg(v: u32) -> u32 {
    let state = v.wrapping_mul(747_796_405).wrapping_add(2_891_336_453);
    let word = ((state >> ((state >> 28) + 4)) ^ state).wrapping_mul(277_803_737);
    (word >> 22) ^ word
}

/// `dbg_hash_u32(v)`: the hash's low three bytes as 8-bit sRGB red, green, blue.
pub fn dbg_hash_u32(v: u32) -> Rgb {
    let h = pcg(v).to_le_bytes();
    srgb8([h[0], h[1], h[2]])
}

/// `dbg_literal(x)`: `0.5 + 0.5 · x/(1 + |x|)`, `x` clamped to ±1e30.
pub fn dbg_literal(x: f64) -> f64 {
    let c = x.clamp(-1e30, 1e30);
    0.5 + 0.5 * c / (1.0 + c.abs())
}

/// `dbg_sentinel(x, frag_xy)`: the hatch for the absence NaN's exact bits, else `x` on the viridis ramp
/// ([`dbg_literal`]).
pub fn dbg_sentinel(x: f32, frag_xy: [f64; 2]) -> Rgb {
    if x.to_bits() == ABSENT_NAN_BITS {
        debug_invalid(frag_xy)
    } else {
        ramp_viridis(dbg_literal(f64::from(x)))
    }
}
