#!/usr/bin/env python3
"""Generate plan/coverage.md from plan/requirements.yaml and plan/section_notes.yaml.

Reports, for every corpus file (plan/tools/sections.py's CORPUS_GLOBS, plus decisions.md):
  - each section that yielded no requirement, with its recorded reason (or an RQ entry);
  - any section that yielded no requirement AND has no recorded reason (an error: exit 1);
  - any cited source that doesn't exist (an error: exit 1);
and the requirement count per area and per milestone.

Usage: python3 plan/tools/coverage.py [--check]   (--check: don't write, just exit non-zero on errors)
"""
import collections, os, re, sys

import yaml

sys.path.insert(0, os.path.dirname(__file__))
from sections import citable_index, corpus_files, section_index, RULINGS_FILE  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
REQS = "plan/requirements.yaml"
NOTES = "plan/section_notes.yaml"
OUT = "plan/coverage.md"
QUEUE = "REVIEW_QUEUE.md"
AREAS = ["DEC", "ENC", "CHART", "INT", "EVT", "PAY", "GEN", "SCHED", "REF", "RENDER", "COL", "GUI", "TOOL", "VAL",
         "PERF", "SYS"]


def main():
    os.chdir(ROOT)
    all_reqs = yaml.safe_load(open(REQS, encoding="utf-8"))
    retired = [r for r in all_reqs if r.get("retired")]
    reqs = [r for r in all_reqs if not r.get("retired")]
    notes = yaml.safe_load(open(NOTES, encoding="utf-8")) or []
    index = section_index(corpus_files() + [RULINGS_FILE])
    citable = citable_index()

    errors = []
    queue = set(re.findall(r"^## (RQ-\d+)\b", open(QUEUE, encoding="utf-8").read(), re.M))
    for r in reqs:
        for q in r.get("rq") or []:
            if q not in queue:
                errors.append(f"{r['id']}: {q} is not in {QUEUE}")
    cited = collections.defaultdict(set)
    for r in reqs:
        for s in r["source"]:
            f, sec = s["file"], s["section"]
            if f not in citable:
                errors.append(f"{r['id']}: source file not in the corpus: {f}")
            elif sec not in citable[f]:
                errors.append(f"{r['id']}: no section {sec!r} in {f}")
            cited[f].add(sec)

    noted = {}
    for n in notes:
        f, sec = n["file"], n["section"]
        if f not in index or sec not in index[f]:
            errors.append(f"section_notes: no section {sec!r} in {f}")
        noted[(f, sec)] = n
        for q in re.findall(r"RQ-\d+", n["reason"]):
            if q not in queue:
                errors.append(f"section_notes: {f} § {sec}: {q} is not in {QUEUE}")

    lines = ["# Requirement coverage", "",
             "*Generated by `plan/tools/coverage.py` from `plan/requirements.yaml` and `plan/section_notes.yaml`. "
             "Do not edit by hand.*", ""]

    by_area = collections.Counter(r["area"] for r in reqs)
    by_ms = collections.Counter(r.get("milestone", "?") for r in reqs)
    lines += ["## Requirements per area", "", "| area | count |", "|---|---|"]
    lines += [f"| {a} | {by_area.get(a, 0)} |" for a in AREAS]
    unknown = sorted(set(by_area) - set(AREAS))
    for a in unknown:
        errors.append(f"unknown area code {a}")
    lines += [f"| **total** | **{len(reqs)}** |", ""]
    by_kind = collections.Counter(r.get("kind", "obligation") for r in reqs)
    lines += ["Of these: " + ", ".join(f"{c} {k}" for k, c in sorted(by_kind.items())) +
              f". Retired (kept for their ids, not counted): {len(retired)}.", ""]
    lines += ["## Requirements per milestone", "", "| milestone | count |", "|---|---|"]
    lines += [f"| {m} | {c} |" for m, c in sorted(by_ms.items())]
    lines += [""]

    total_secs = sum(len(v) for v in index.values())
    covered = sum(1 for f, hs in index.items() for h in hs if h in cited[f])
    lines += ["## Sections", "",
              f"{total_secs} sections in {len(index)} files: {covered} yield at least one requirement; "
              f"{total_secs - covered} yield none and are listed below with the reason.", ""]

    reason_count = collections.Counter()
    for f in sorted(index):
        rows = []
        for h in index[f]:
            if h in cited[f]:
                continue
            n = noted.get((f, h))
            if n is None:
                errors.append(f"uncovered section with no reason: {f} § {h}")
                rows.append(f"| {h} | **MISSING REASON** | |")
                continue
            reason_count[n["reason"]] += 1
            rows.append(f"| {h} | {n['reason']} | {n.get('note', '')} |".replace("\n", " "))
        if rows:
            lines += [f"### `{f}`", "", "| section | reason | note |", "|---|---|---|"] + rows + [""]

    lines[lines.index("## Sections") + 3:lines.index("## Sections") + 3] = [
        "| reason | sections |", "|---|---|"] + [f"| {k} | {v} |" for k, v in sorted(reason_count.items())] + [""]

    if errors:
        lines += ["## Errors", ""] + [f"- {e}" for e in errors] + [""]

    if "--check" not in sys.argv:
        with open(OUT, "w", encoding="utf-8") as fh:
            fh.write("\n".join(lines))
    for e in errors:
        print("ERROR:", e, file=sys.stderr)
    print(f"{len(reqs)} requirements ({len(retired)} retired not counted); {covered}/{total_secs} sections cited; "
          f"{len(errors)} errors")
    sys.exit(1 if errors else 0)


if __name__ == "__main__":
    main()
