#!/usr/bin/env python3
"""Generate plan/CURRENT_RULES.md from decisions.md and plan/rule_groups.yaml (R-292).

CURRENT_RULES.md lists every ruling in force, grouped, each under its number, with its decisions.md heading and the
rulings that amend it (its forward lines, plan/tools/rulings.py). A ruling with a "Superseded by R-n" forward line (not
"in part") is left out. The one-off acts are listed last, as history only.

Fails if an entry of decisions.md is in no group or in two, if a group names an entry decisions.md lacks, or (with
--check) if CURRENT_RULES.md differs from what this would write.

Usage: python3 plan/tools/current_rules.py [--check]   (--check: don't write, just exit non-zero if it's stale)
"""
import os, re, sys

import yaml

sys.path.insert(0, os.path.dirname(__file__))
from rulings import FORWARD, RULINGS, entries  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
GROUPS = "plan/rule_groups.yaml"
OUT = "plan/CURRENT_RULES.md"
# A forward line of its own, directly under the heading: "*Amended by R-10.*"
OWN_LINE = re.compile(r"^\*((?:Amended|Superseded|Corrected|Replaced|Reversed|Refined|Extended)\b.*?)\.?\*$")

HEADER = [
    "# Current rules",
    "",
    "*Generated by `plan/tools/current_rules.py` from `decisions.md` and `plan/rule_groups.yaml`. Do not edit by hand:",
    "`python3 plan/check_plan.py` fails if this file is stale (R-292).*",
    "",
    "Every ruling in force, grouped, each under its number. The line is the ruling's heading in `decisions.md`, which",
    "holds its full text and why it was made. An amended ruling names the rulings that amend it; read them with it. A",
    "superseded ruling is left out. The one-off acts, such as a split, an acceptance or a merge, come last, as history",
    "only.",
]


def notes(entry):
    """The entry's forward notes, in order: each own forward line's text, and each "amended by R-n" in its date line."""
    out = []
    for line in entry["head"]:
        m = OWN_LINE.match(line.strip())
        if m:
            out.append(m.group(1)[0].lower() + m.group(1)[1:])
        else:
            out += [f"{v.lower()}{p or ''} by {ids}" for v, p, ids in FORWARD.findall(line)]
    return out


def superseded(entry):
    return any(v.lower() == "superseded" and not p for line in entry["head"] for v, p, _ in FORWARD.findall(line))


def build():
    es = entries()
    by_key = {e["key"]: e for e in es}
    spec = yaml.safe_load(open(GROUPS, encoding="utf-8"))
    errors, where = [], {}
    for g, body in spec["groups"].items():
        for k in body["rules"]:
            if k in where:
                errors.append(f"{GROUPS}: {k} is in both {where[k]} and {g}")
            where[k] = g
    for k in spec.get("not_rules") or []:
        if k in where:
            errors.append(f"{GROUPS}: {k} is in both {where[k]} and not_rules")
        where[k] = "not_rules"
    for k in where:
        if k not in by_key:
            errors.append(f"{GROUPS}: {k} is not an entry in {RULINGS}")
    for e in es:
        if e["key"] not in where:
            errors.append(f"{GROUPS}: {RULINGS}'s entry {e['key']} is in no group")

    lines = list(HEADER)
    for g, body in spec["groups"].items():
        lines += ["", f"## {body['title']}", ""]
        for e in es:  # file order is ruling order, save R-196/R-197 and R-206/R-207, which were recorded out of turn
            if where.get(e["key"]) != g or superseded(e):
                continue
            label = e["key"] + (" ✱" if e["star"] else "")
            title = e["title"] if e["id"] else e["title"].split(" — ", 1)[-1]
            n = "; ".join(notes(e))
            lines.append(f"- **{label}** — {title}" + (f". {n[0].upper()}{n[1:]}." if n else ""))
    return "\n".join(lines) + "\n", errors


def main():
    os.chdir(ROOT)
    text, errors = build()
    if not errors:
        if "--check" in sys.argv:
            current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
            if current != text:
                errors.append(f"{OUT} is stale: run python3 plan/tools/current_rules.py")
        else:
            with open(OUT, "w", encoding="utf-8") as fh:
                fh.write(text)
    for e in errors:
        print("ERROR:", e, file=sys.stderr)
    print(f"{OUT}: {text.count(chr(10) + '- **')} rulings listed; {len(errors)} errors")
    sys.exit(1 if errors else 0)


if __name__ == "__main__":
    main()
