#!/usr/bin/env python3
"""Generate plan/CURRENT_RULES.md from decisions.md and plan/rule_groups.yaml (R-292).

CURRENT_RULES.md lists every ruling in force, grouped, each under its number, with its decisions.md heading. A ruling
amended in part also gives its "Still in force" line and the rulings that amend it (its forward lines,
plan/tools/rulings.py). A ruling with a "Superseded by R-n" forward line (not "in part") is left out (R-293). The
one-off acts are listed last, as history only.

Fails if an entry of decisions.md is in no group or in two, if a group names an entry decisions.md lacks, or (with
--check) if CURRENT_RULES.md differs from what this would write.

Usage: python3 plan/tools/current_rules.py [--check]   (--check: don't write, just exit non-zero if it's stale)
"""
import os, sys

import yaml

sys.path.insert(0, os.path.dirname(__file__))
from rulings import RULINGS, entries, forward_notes, still_in_force, superseded  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
GROUPS = "plan/rule_groups.yaml"
OUT = "plan/CURRENT_RULES.md"

HEADER = [
    "# Current rules",
    "",
    "*Generated by `plan/tools/current_rules.py` from `decisions.md` and `plan/rule_groups.yaml`. Do not edit by hand:",
    "`python3 plan/check_plan.py` fails if this file is stale (R-292).*",
    "",
    "Every ruling in force, grouped, each under its number. The line is the ruling's heading in `decisions.md`, which",
    "holds its full text and why it was made. A ruling amended in part says what of it is still in force and names the",
    "rulings that amend it; read them with it. A ruling superseded outright is left out, and the ruling that supersedes",
    "it is listed (R-293). The one-off acts, such as a split, an acceptance or a merge, come last, as history only.",
]


def build():
    es = entries()
    by_key = {e["key"]: e for e in es}
    spec = yaml.safe_load(open(GROUPS, encoding="utf-8"))
    errors, where = [], {}
    for g, body in spec["groups"].items():
        for k in body["rules"]:
            if k in where:
                errors.append(f"{GROUPS}: {k} is in both {where[k]} and {g}")
            where[k] = g
    for k in spec.get("not_rules") or []:
        if k in where:
            errors.append(f"{GROUPS}: {k} is in both {where[k]} and not_rules")
        where[k] = "not_rules"
    for k in where:
        if k not in by_key:
            errors.append(f"{GROUPS}: {k} is not an entry in {RULINGS}")
    for e in es:
        if e["key"] not in where:
            errors.append(f"{GROUPS}: {RULINGS}'s entry {e['key']} is in no group")

    lines = list(HEADER)
    for g, body in spec["groups"].items():
        lines += ["", f"## {body['title']}", ""]
        for e in es:  # file order is ruling order, save R-196/R-197 and R-206/R-207, which were recorded out of turn
            if where.get(e["key"]) != g or superseded(e):
                continue
            label = e["key"] + (" ✱" if e["star"] else "")
            title = e["title"] if e["id"] else e["title"].split(" — ", 1)[-1]
            parts = [f"Still in force: {still_in_force(e).rstrip('.')}"] if still_in_force(e) else []
            n = "; ".join(forward_notes(e))
            parts += [f"{n[0].upper()}{n[1:]}"] if n else []
            lines.append(f"- **{label}** — {title}" + "".join(f". {p}" for p in parts) + ("." if parts else ""))
    return "\n".join(lines) + "\n", errors


def main():
    os.chdir(ROOT)
    text, errors = build()
    if not errors:
        if "--check" in sys.argv:
            current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
            if current != text:
                errors.append(f"{OUT} is stale: run python3 plan/tools/current_rules.py")
        else:
            with open(OUT, "w", encoding="utf-8") as fh:
                fh.write(text)
    for e in errors:
        print("ERROR:", e, file=sys.stderr)
    print(f"{OUT}: {text.count(chr(10) + '- **')} rulings listed; {len(errors)} errors")
    sys.exit(1 if errors else 0)


if __name__ == "__main__":
    main()
