//! Generated by `cargo xtask codegen` from the layout table (`crates/ledger/src/payload.rs`); do not edit.
//! The host export decoder (render contract Part 5 (c); dd_generation_root §1, seam 13): every ledger field of
//! one sample decoded from the packed payload.

use kernel::payload::*;

/// Every ledger field of one sample, decoded: one member per entry, in the ledger's order (dd_generation_root
/// §3). A vector is flat, component `2j` and `2j + 1` from slot `j` (§3.8).
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Decoded {
    pub r: [f32; 6],
    pub p: [f32; 6],
    pub r_sh: [f32; 6],
    pub p_sh: [f32; 6],
    pub S: f32,
    pub theta: f32,
    pub mean_y: f32,
    pub C_ty: f32,
    pub E_0: f32,
    pub Lz_0: f32,
    pub total_substeps: u32,
    pub closure_min: f32,
    pub closure_step: u32,
    pub state: u32,
    pub detail: u32,
    pub saturated: bool,
    pub dmin_pair: u32,
    pub last_symbol: u32,
    pub d_min: f32,
    pub dE_max: f32,
    pub dLz_max: f32,
    pub t_end_step: u32,
    pub t_dmin_step: u32,
    pub ftle: f32,
    pub energy_drift: f32,
    pub Lz_drift: f32,
    pub diffusion: f32,
    pub n: [f32; 3],
    pub m0: f32,
    pub m1: f32,
    pub m2: f32,
    pub q_mass: f32,
    pub rho_mag: f32,
    pub lambda_mag: f32,
    pub rho_ratio: f32,
    pub rho_angle: f32,
    pub K_0: f32,
    pub V_0: f32,
    pub virial_ratio: f32,
    pub r_min_pair_0: f32,
    pub payload: u32,
    pub length: u32,
}

/// The stored sample `s`, its word `word` and its `ICDescriptor` `ic`, decoded at `params`: each field the read side
/// holds through the Rust read side (lowering Part 3a), the word bound and E = 0, with the descriptor's masses; a word
/// field through its word accessor; the shadow from `s`; an `ICDescriptor` field from `ic`.
pub fn decode(s: &SimStateFTLE, word: [u32; 4], ic: &ICDescriptor, params: &ReadParams) -> Decoded {
    let read = sim_state_from_ftle(
        s,
        word,
        true,
        canonical_nan(),
        false,
        [ic.m0, ic.m1, ic.m2],
        params,
    );
    Decoded {
        r: flat(read.r),
        p: flat(read.p),
        r_sh: flat(read.r_sh),
        p_sh: flat(read.p_sh),
        S: read.S,
        theta: read.theta,
        mean_y: read.mean_y,
        C_ty: read.C_ty,
        E_0: read.E_0,
        Lz_0: read.Lz_0,
        total_substeps: read.total_substeps,
        closure_min: read.closure_min,
        closure_step: read.closure_step,
        state: read.state,
        detail: read.detail,
        saturated: read.saturated,
        dmin_pair: read.dmin_pair,
        last_symbol: read.last_symbol,
        d_min: read.d_min,
        dE_max: read.dE_max,
        dLz_max: read.dLz_max,
        t_end_step: read.t_end_step,
        t_dmin_step: read.t_dmin_step,
        ftle: read.ftle,
        energy_drift: read.energy_drift,
        Lz_drift: read.Lz_drift,
        diffusion: read.diffusion,
        n: read.n,
        m0: ic.m0,
        m1: ic.m1,
        m2: ic.m2,
        q_mass: ic.q_mass,
        rho_mag: ic.rho_mag,
        lambda_mag: ic.lambda_mag,
        rho_ratio: ic.rho_ratio,
        rho_angle: ic.rho_angle,
        K_0: ic.K_0,
        V_0: ic.V_0,
        virial_ratio: ic.virial_ratio,
        r_min_pair_0: ic.r_min_pair_0,
        payload: fgw_payload(read.word),
        length: fgw_length_raw(read.word),
    }
}

/// A vec2-grouped vector, flat: slot `j`'s two components at `2j` and `2j + 1` (dd_generation_root §3.8).
fn flat(v: [[f32; 2]; 3]) -> [f32; 6] {
    [v[0][0], v[0][1], v[1][0], v[1][1], v[2][0], v[2][1]]
}
