//! Generated by `cargo xtask codegen` from the layout table (`crates/ledger/src/payload.rs`); do not edit.

/// `SimStateFTLE`: 144 B, aligned to 8 (dd_simstate_payload §1; dd_generation_root §3.3a, §3.6).
#[repr(C, align(8))]
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct SimStateFTLE {
    pub r: [[f32; 2]; 3],
    pub p: [[f32; 2]; 3],
    pub r_sh: [[f32; 2]; 3],
    pub p_sh: [[f32; 2]; 3],
    pub S: f32,
    pub theta: f32,
    pub mean_y: f32,
    pub C_ty: f32,
    pub E_0: f32,
    pub Lz_0: f32,
    pub packed_a: u32,
    pub packed_b: u32,
    pub times: u32,
    pub total_substeps: u32,
    pub closure_min: f32,
    pub closure_step: u16,
    pub _reserved: u16,
}

/// `SimStateBase`: 96 B, aligned to 8 (dd_simstate_payload §1; dd_generation_root §3.3a, §3.6).
#[repr(C, align(8))]
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct SimStateBase {
    pub r: [[f32; 2]; 3],
    pub p: [[f32; 2]; 3],
    pub S: f32,
    pub theta: f32,
    pub mean_y: f32,
    pub C_ty: f32,
    pub E_0: f32,
    pub Lz_0: f32,
    pub packed_a: u32,
    pub packed_b: u32,
    pub times: u32,
    pub total_substeps: u32,
    pub closure_min: f32,
    pub closure_step: u16,
    pub _reserved: u16,
}

/// `FreeGroupWord`: 16 B, aligned to 16 (dd_simstate_payload §1; dd_generation_root §3.3a, §3.6).
#[repr(C, align(16))]
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct FreeGroupWord {
    pub free_group_word: [u32; 4],
}

/// `ICDescriptor`: 64 B, aligned to 4 (dd_simstate_payload §1; dd_generation_root §3.3a, §3.6).
#[repr(C, align(4))]
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct ICDescriptor {
    pub m0: f32,
    pub m1: f32,
    pub m2: f32,
    pub q_mass: f32,
    pub rho_mag: f32,
    pub lambda_mag: f32,
    pub rho_ratio: f32,
    pub rho_angle: f32,
    pub K_0: f32,
    pub V_0: f32,
    pub virial_ratio: f32,
    pub r_min_pair_0: f32,
    pub _pad: [u32; 4],
}
