//! Generated by `cargo xtask codegen` from the layout table (`crates/ledger/src/payload.rs`); do not edit.

/// The payload schema version: the 64-bit FNV-1a hash of the canonicalised ledger, computed at generation
/// and never bumped by hand (R-36, R-63; `ledger::version`).
pub const PAYLOAD_SCHEMA_VERSION: u64 = 0x687c1f2122b17d0b;

/// `SimStateFTLE` at the `Real` `R`: 144 B aligned to 8 at f32, 272 B aligned to 8 at f64.
/// Its f32 members are `R`; `_tail` is its declared tail padding (dd_simstate_payload §1; philosophy §7.1; R-86).
#[repr(C, align(8))]
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct SimStateFTLEOf<R: PayloadReal> {
    pub r: [[R; 2]; 3],
    pub p: [[R; 2]; 3],
    pub r_sh: [[R; 2]; 3],
    pub p_sh: [[R; 2]; 3],
    pub S: R,
    pub theta: R,
    pub mean_y: R,
    pub C_ty: R,
    pub E_0: R,
    pub Lz_0: R,
    pub packed_a: u32,
    pub packed_b: u32,
    pub times: u32,
    pub total_substeps: u32,
    pub closure_min: R,
    pub closure_step: u16,
    pub _reserved: u16,
    pub _tail: R::SimStateFTLETail,
}

/// `SimStateFTLE` at f32, the GPU's instantiation (canonical_spec §1 item 3): 144 B.
pub type SimStateFTLE = SimStateFTLEOf<f32>;

/// `SimStateBase` at the `Real` `R`: 96 B aligned to 8 at f32, 176 B aligned to 8 at f64.
/// Its f32 members are `R`; `_tail` is its declared tail padding (dd_simstate_payload §1; philosophy §7.1; R-86).
#[repr(C, align(8))]
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct SimStateBaseOf<R: PayloadReal> {
    pub r: [[R; 2]; 3],
    pub p: [[R; 2]; 3],
    pub S: R,
    pub theta: R,
    pub mean_y: R,
    pub C_ty: R,
    pub E_0: R,
    pub Lz_0: R,
    pub packed_a: u32,
    pub packed_b: u32,
    pub times: u32,
    pub total_substeps: u32,
    pub closure_min: R,
    pub closure_step: u16,
    pub _reserved: u16,
    pub _tail: R::SimStateBaseTail,
}

/// `SimStateBase` at f32, the GPU's instantiation (canonical_spec §1 item 3): 96 B.
pub type SimStateBase = SimStateBaseOf<f32>;

/// `FreeGroupWord`: 16 B, aligned to 16 (dd_simstate_payload §1; dd_generation_root §3.3a, §3.6).
#[repr(C, align(16))]
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct FreeGroupWord {
    pub free_group_word: [u32; 4],
}

/// `ICDescriptor` at the `Real` `R`: 64 B aligned to 4 at f32, 112 B aligned to 8 at f64.
/// Its f32 members are `R`; `_tail` is its declared tail padding (dd_generation_root §3.6; R-313; philosophy §7.1; R-86).
#[repr(C, align(4))]
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct ICDescriptorOf<R: PayloadReal> {
    pub m0: R,
    pub m1: R,
    pub m2: R,
    pub q_mass: R,
    pub rho_mag: R,
    pub lambda_mag: R,
    pub rho_ratio: R,
    pub rho_angle: R,
    pub K_0: R,
    pub V_0: R,
    pub virial_ratio: R,
    pub r_min_pair_0: R,
    pub _pad: [u32; 4],
    pub _tail: R::ICDescriptorTail,
}

/// `ICDescriptor` at f32, the GPU's instantiation (canonical_spec §1 item 3): 64 B.
pub type ICDescriptor = ICDescriptorOf<f32>;

/// A `Real` the payload is instantiated at (R-265), with the declared tail padding (R-86) of each struct generic
/// over it at its width (dd_simstate_payload §1).
pub trait PayloadReal: crate::Real {
    type SimStateFTLETail: Copy + Default + core::fmt::Debug + PartialEq;
    type SimStateBaseTail: Copy + Default + core::fmt::Debug + PartialEq;
    type ICDescriptorTail: Copy + Default + core::fmt::Debug + PartialEq;
}

impl PayloadReal for f32 {
    type SimStateFTLETail = [u32; 0];
    type SimStateBaseTail = [u32; 0];
    type ICDescriptorTail = [u32; 0];
}

impl PayloadReal for f64 {
    type SimStateFTLETail = [u32; 1];
    type SimStateBaseTail = [u32; 1];
    type ICDescriptorTail = [u32; 0];
}

/// A precision row of the payload (dd_simstate_payload §1): the float type, its size and alignment in bytes, whether
/// the kernel is instantiated at it (R-265), and each struct generic over it as `(name, size, alignment)` at it:
/// the `SimState` structs as `structs`, `ICDescriptor` as `descriptor` (dd_generation_root §3.6; R-313).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct PayloadLayout {
    pub real: &'static str,
    pub real_size: usize,
    pub real_align: usize,
    pub instantiated: bool,
    pub structs: [(&'static str, usize, usize); 2],
    pub descriptor: (&'static str, usize, usize),
}

/// The payload's layout at each precision row, f32 first; a row not instantiated is a stub for the width function
/// only (dd_simstate_payload §1; philosophy §7.1).
pub const PAYLOAD_LAYOUTS: [PayloadLayout; 3] = [
    PayloadLayout {
        real: "f32",
        real_size: 4,
        real_align: 4,
        instantiated: true,
        structs: [("SimStateFTLE", 144, 8), ("SimStateBase", 96, 8)],
        descriptor: ("ICDescriptor", 64, 4),
    },
    PayloadLayout {
        real: "f64",
        real_size: 8,
        real_align: 8,
        instantiated: true,
        structs: [("SimStateFTLE", 272, 8), ("SimStateBase", 176, 8)],
        descriptor: ("ICDescriptor", 112, 8),
    },
    PayloadLayout {
        real: "DoubleF64",
        real_size: 16,
        real_align: 8,
        instantiated: false,
        structs: [("SimStateFTLE", 520, 8), ("SimStateBase", 328, 8)],
        descriptor: ("ICDescriptor", 208, 8),
    },
];

/// The `state` code of escape (payload §2).
pub const STATE_ESCAPE: u32 = 0;

/// The `state` code of bounded (payload §2).
pub const STATE_BOUNDED: u32 = 1;

/// The `state` code of collision (payload §2).
pub const STATE_COLLISION: u32 = 2;

/// The `state` code of running (payload §2).
pub const STATE_RUNNING: u32 = 3;

/// The `state` code of sim_failed (payload §2).
pub const STATE_SIM_FAILED: u32 = 4;

/// The `state` code of decode_failed (payload §2).
pub const STATE_DECODE_FAILED: u32 = 5;

/// binary16's greatest finite value, the pack clamp (payload §1; the register's `f16_finite_max`).
pub const F16_FINITE_MAX: f32 = 65504.0;

/// binary16's smallest positive subnormal, 2⁻²⁴, and its bits (R-271; the register's `f16_min_subnormal`, R-278).
pub const F16_MIN_SUBNORMAL: f32 = 5.9604645e-8;
pub const F16_MIN_SUBNORMAL_BITS: u32 = 0x0001;

/// Bits `offset .. offset + width` of `w`, `width` in 1..=32 (the u32 `extractBits`, payload §6).
#[inline]
pub const fn extract(w: u32, offset: u32, width: u32) -> u32 {
    (w >> offset) & (u32::MAX >> (32 - width))
}

/// `w` with bits `offset .. offset + width` replaced by the low `width` bits of `v`, every other bit kept (the u32
/// `insertBits`, payload §6).
#[inline]
pub const fn insert(w: u32, v: u32, offset: u32, width: u32) -> u32 {
    let mask = (u32::MAX >> (32 - width)) << offset;
    (w & !mask) | ((v << offset) & mask)
}

/// `x` clamped to binary16's finite range, ±65504, as payload §1 requires before packing; NaN stays NaN.
#[inline]
pub fn clamp_f16(x: f32) -> f32 {
    x.clamp(-F16_FINITE_MAX, F16_FINITE_MAX)
}

/// The binary16 bits of `x`, rounded to nearest, ties to even: one of the two results WGSL's `pack2x16float` may give
/// for an inexact value, and the exact one otherwise, subnormals kept. Past the finite range the result is ±∞, where
/// `pack2x16float` is indeterminate, so packers clamp first (payload §1). NaN stays NaN, keeping its payload's top bits.
pub fn f32_to_f16_bits(x: f32) -> u16 {
    let b = x.to_bits();
    let sign = ((b >> 16) & 0x8000) as u16;
    let exp = ((b >> 23) & 0xff) as i32;
    let man = b & 0x007f_ffff;
    if exp == 0xff {
        let payload = (man >> 13) as u16;
        let nan = if man != 0 && payload == 0 {
            0x0200
        } else {
            payload
        };
        return sign | 0x7c00 | nan;
    }
    let e = exp - 112;
    if e >= 0x1f {
        return sign | 0x7c00;
    }
    let (full, shift) = if e <= 0 {
        (man | 0x0080_0000, (14 - e) as u32)
    } else {
        (man, 13)
    };
    if shift >= 32 {
        return sign;
    }
    let q = full >> shift;
    let rem = full & ((1 << shift) - 1);
    let half = 1 << (shift - 1);
    let q = if rem > half || (rem == half && q & 1 == 1) {
        q + 1
    } else {
        q
    };
    let h = if e <= 0 { q } else { ((e as u32) << 10) + q };
    sign | h as u16
}

/// The f32 value of the binary16 bits `h`, exact for every one of them (`unpack2x16float`'s conversion).
pub fn f16_bits_to_f32(h: u16) -> f32 {
    let sign = u32::from(h & 0x8000) << 16;
    let exp = u32::from((h >> 10) & 0x1f);
    let man = u32::from(h & 0x03ff);
    if exp == 0 {
        let magnitude = man as f32 * F16_MIN_SUBNORMAL;
        return f32::from_bits(sign | magnitude.to_bits());
    }
    if exp == 0x1f {
        return f32::from_bits(sign | 0x7f80_0000 | (man << 13));
    }
    f32::from_bits(sign | ((exp + 112) << 23) | (man << 13))
}

/// WGSL's `pack2x16float`: `v[0]` in bits 0–15, `v[1]` in bits 16–31. No clamp: callers clamp first (payload §1).
#[inline]
pub fn pack2x16float(v: [f32; 2]) -> u32 {
    u32::from(f32_to_f16_bits(v[0])) | (u32::from(f32_to_f16_bits(v[1])) << 16)
}

/// WGSL's `unpack2x16float`: `[bits 0–15, bits 16–31]` (`.x`, `.y`).
#[inline]
pub fn unpack2x16float(w: u32) -> [f32; 2] {
    [f16_bits_to_f32(w as u16), f16_bits_to_f32((w >> 16) as u16)]
}

/// Escape, bounded or collision: a resolved outcome. sim_failed and decode_failed are finished but not resolved, so
/// never gate re-dispatch on this (payload §6).
#[inline]
pub fn sd_is_resolved_outcome(w: u32) -> bool {
    let s = sd_state(w);
    s == STATE_ESCAPE || s == STATE_BOUNDED || s == STATE_COLLISION
}

/// Still marching: `STATE_RUNNING` (payload §6).
#[inline]
pub fn sd_is_running(w: u32) -> bool {
    sd_state(w) == STATE_RUNNING
}

/// Untrusted: neither a resolved outcome nor running, so sim_failed, decode_failed and the reserved codes (payload §2,
/// §6).
#[inline]
pub fn sd_is_failed(w: u32) -> bool {
    !sd_is_resolved_outcome(w) && !sd_is_running(w)
}

/// Finished, so the scheduler stops marching it: every state but running, the reserved 6–7 included (payload §2, §6).
#[inline]
pub fn sd_is_finished(w: u32) -> bool {
    !sd_is_running(w)
}

/// Whether `last_symbol` is meaningful, from the sidecar word's `length_raw`: at least 1 and not the truncation
/// sentinel (payload §2, §6).
#[inline]
pub fn sd_last_symbol_valid(len: u32) -> bool {
    len >= 1 && len != 127
}

/// The complexity proxy, ⌊log₂ total⌋ and 0 for a total ≤ 1, derived from the exact `total_substeps` (payload §6, R-86).
#[inline]
pub fn total_substeps_log2(total: u32) -> u32 {
    if total > 1 {
        31 - total.leading_zeros()
    } else {
        0
    }
}

/// `t_end_step / horizon_steps`, 0 when `horizon_steps` is 0 (payload §2, §6).
#[inline]
pub fn tm_t_end_fraction(w: u32, horizon_steps: u32) -> f32 {
    if horizon_steps > 0 {
        tm_t_end_step(w) as f32 / horizon_steps as f32
    } else {
        0.0
    }
}

/// `t_dmin_step / horizon_steps`, 0 when `horizon_steps` is 0 (payload §2, §6).
#[inline]
pub fn tm_t_dmin_fraction(w: u32, horizon_steps: u32) -> f32 {
    if horizon_steps > 0 {
        tm_t_dmin_step(w) as f32 / horizon_steps as f32
    } else {
        0.0
    }
}

/// `state`: bits 0–2 of `packed_a` (payload §2, §6).
#[inline]
pub fn sd_state(w: u32) -> u32 {
    extract(w, 0, 3)
}

/// `packed_a` with `state` set to `v`; every other bit kept.
#[inline]
pub fn set_state(w: u32, v: u32) -> u32 {
    insert(w, v, 0, 3)
}

/// `detail`: bits 3–4 of `packed_a` (payload §2, §6).
#[inline]
pub fn sd_detail(w: u32) -> u32 {
    extract(w, 3, 2)
}

/// `packed_a` with `detail` set to `v`; every other bit kept.
#[inline]
pub fn set_detail(w: u32, v: u32) -> u32 {
    insert(w, v, 3, 2)
}

/// `saturated`: bit 5 of `packed_a` (payload §2, §6).
#[inline]
pub fn sd_saturated(w: u32) -> bool {
    extract(w, 5, 1) == 1
}

/// `packed_a` with `saturated` set to `v`; every other bit kept.
#[inline]
pub fn set_saturated(w: u32, v: bool) -> u32 {
    insert(w, u32::from(v), 5, 1)
}

/// `dmin_pair`'s sentinel in the ledger (dd_generation_root §3.8).
pub const SD_DMIN_PAIR_SENTINEL: u32 = 3;

/// `dmin_pair`: bits 6–7 of `packed_a` (payload §2, §6).
#[inline]
pub fn sd_dmin_pair(w: u32) -> u32 {
    extract(w, 6, 2)
}

/// `packed_a` with `dmin_pair` set to `v`; every other bit kept.
#[inline]
pub fn set_dmin_pair(w: u32, v: u32) -> u32 {
    insert(w, v, 6, 2)
}

/// `last_symbol`: bits 8–9 of `packed_a` (payload §2, §6).
#[inline]
pub fn sd_last_symbol(w: u32) -> u32 {
    extract(w, 8, 2)
}

/// `packed_a` with `last_symbol` set to `v`; every other bit kept.
#[inline]
pub fn set_last_symbol(w: u32, v: u32) -> u32 {
    insert(w, v, 8, 2)
}

/// `d_min`'s sentinel in the ledger (dd_generation_root §3.8).
pub const PA_D_MIN_SENTINEL: f32 = f32::from_bits(0x7f80_0000);

/// `d_min`: bits 16–31 of `packed_a` (payload §2, §6).
#[inline]
pub fn pa_d_min(w: u32) -> f32 {
    f16_bits_to_f32(extract(w, 16, 16) as u16)
}

/// `d_min`'s unset bits: f16 +∞, the minimum of an empty set (R-271).
pub const PA_D_MIN_UNSET: u32 = 0x7c00;

/// Whether `d_min` is unset: tested by its bits, never by a float comparison (R-271).
#[inline]
pub fn pa_d_min_is_unset(w: u32) -> bool {
    extract(w, 16, 16) == PA_D_MIN_UNSET
}

/// `packed_a` with `d_min` unset: a failed sample's, and any sample's before its first step (R-271).
#[inline]
pub fn set_d_min_unset(w: u32) -> u32 {
    insert(w, PA_D_MIN_UNSET, 16, 16)
}

/// `packed_a` with `d_min` set to `v` (R-271, payload §1): +∞, tested by its f32 bits, writes the unset bits; a value
/// below f16's smallest positive subnormal, 2⁻²⁴, writes that subnormal (`0x0001`), so 0.0 never appears; both
/// are written as bits, not through the conversion. Otherwise `v` is clamped to ±65504 and converted.
///
/// Storage never holds NaN (R-79) and a negative value is never silently rewritten (R-281): each is a
/// `debug_assert!` failure. The release behaviour is [`set_d_min_release`]'s, counting into `counters`, the
/// frame's pair that the caller passes in and reads back (R-288, R-294).
#[inline]
pub fn set_d_min(w: u32, v: f32, counters: &super::DminCounters) -> u32 {
    debug_assert!(
        !v.is_nan(),
        "`d_min` is NaN: storage never holds NaN (R-79, R-281)"
    );
    debug_assert!(
        v.is_nan() || v >= 0.0,
        "`d_min` is negative: it is never silently rewritten (R-281)"
    );
    set_d_min_release(w, v, counters)
}

/// [`set_d_min`] without its debug assertions, as a release build runs it (R-281): NaN writes the unset
/// bits (never NaN, R-79) and counts it with `counters.increment_nan_unset()`; a negative value
/// writes the floor `0x0001` and counts it with `counters.increment_negative_floored()`; any other
/// value below 2⁻²⁴, −0.0 included, writes the floor uncounted. The counts are made in release builds
/// as well as debug ones (R-288; telemetry §2). The pair's fields are private (R-300).
#[inline]
pub fn set_d_min_release(w: u32, v: f32, counters: &super::DminCounters) -> u32 {
    let h = if v.is_nan() {
        counters.increment_nan_unset();
        PA_D_MIN_UNSET
    } else if v.to_bits() == 0x7f80_0000 {
        PA_D_MIN_UNSET
    } else if v < 0.0 {
        counters.increment_negative_floored();
        F16_MIN_SUBNORMAL_BITS
    } else if v < F16_MIN_SUBNORMAL {
        F16_MIN_SUBNORMAL_BITS
    } else {
        u32::from(f32_to_f16_bits(clamp_f16(v)))
    };
    insert(w, h, 16, 16)
}

/// `packed_a`'s reserved spans, `(offset, width)`, as the ledger declares them: never written, decoded as zero
/// (payload §2; dd_generation_root §5 test 1).
pub const PACKED_A_RESERVED: [(u32, u32); 1] = [(10, 6)];

/// `packed_a` from its fields, each written in bit order over zero, so its reserved bits are zero (payload §2).
#[inline]
pub fn pack_packed_a(
    state: u32,
    detail: u32,
    saturated: bool,
    dmin_pair: u32,
    last_symbol: u32,
    d_min: f32,
    counters: &super::DminCounters,
) -> u32 {
    let w = set_state(0, state);
    let w = set_detail(w, detail);
    let w = set_saturated(w, saturated);
    let w = set_dmin_pair(w, dmin_pair);
    let w = set_last_symbol(w, last_symbol);
    set_d_min(w, d_min, counters)
}

/// `dE_max`: bits 0–15 of `packed_b` (payload §2, §6).
#[inline]
pub fn pb_dE_max(w: u32) -> f32 {
    f16_bits_to_f32(extract(w, 0, 16) as u16)
}

/// `packed_b` with `dE_max` set to `v`, clamped to ±65504 first (payload §1); every other bit kept.
#[inline]
pub fn set_dE_max(w: u32, v: f32) -> u32 {
    insert(w, u32::from(f32_to_f16_bits(clamp_f16(v))), 0, 16)
}

/// `dLz_max`: bits 16–31 of `packed_b` (payload §2, §6).
#[inline]
pub fn pb_dLz_max(w: u32) -> f32 {
    f16_bits_to_f32(extract(w, 16, 16) as u16)
}

/// `packed_b` with `dLz_max` set to `v`, clamped to ±65504 first (payload §1); every other bit kept.
#[inline]
pub fn set_dLz_max(w: u32, v: f32) -> u32 {
    insert(w, u32::from(f32_to_f16_bits(clamp_f16(v))), 16, 16)
}

/// `packed_b`'s reserved spans, `(offset, width)`, as the ledger declares them: never written, decoded as zero
/// (payload §2; dd_generation_root §5 test 1).
pub const PACKED_B_RESERVED: [(u32, u32); 0] = [];

/// `packed_b` from its fields, each written in bit order over zero, so its reserved bits are zero (payload §2).
#[inline]
pub fn pack_packed_b(dE_max: f32, dLz_max: f32) -> u32 {
    let w = set_dE_max(0, dE_max);
    set_dLz_max(w, dLz_max)
}

/// `t_end_step`: bits 0–15 of `times` (payload §2, §6).
#[inline]
pub fn tm_t_end_step(w: u32) -> u32 {
    extract(w, 0, 16)
}

/// `times` with `t_end_step` set to `v`; every other bit kept.
#[inline]
pub fn set_t_end_step(w: u32, v: u32) -> u32 {
    insert(w, v, 0, 16)
}

/// `t_dmin_step`: bits 16–31 of `times` (payload §2, §6).
#[inline]
pub fn tm_t_dmin_step(w: u32) -> u32 {
    extract(w, 16, 16)
}

/// `times` with `t_dmin_step` set to `v`; every other bit kept.
#[inline]
pub fn set_t_dmin_step(w: u32, v: u32) -> u32 {
    insert(w, v, 16, 16)
}

/// `times`'s reserved spans, `(offset, width)`, as the ledger declares them: never written, decoded as zero
/// (payload §2; dd_generation_root §5 test 1).
pub const TIMES_RESERVED: [(u32, u32); 0] = [];

/// `times` from its fields, each written in bit order over zero, so its reserved bits are zero (payload §2).
#[inline]
pub fn pack_times(t_end_step: u32, t_dmin_step: u32) -> u32 {
    let w = set_t_end_step(0, t_end_step);
    set_t_dmin_step(w, t_dmin_step)
}

/// The word's capacity in symbols, `length`'s greatest valid value (payload §3; the register's `fgw_capacity`).
pub const FGW_CAPACITY: u32 = 76;

/// `length`'s sentinel in the ledger: the word is truncated (payload §3; dd_generation_root §3.8).
pub const FGW_LENGTH_SENTINEL: u32 = 127;

/// `length_raw`: bits 25–31 of the word's `.w`, element 3 of its `vec4<u32>`; 0…76 valid, 127 truncated
/// (payload §3). Never a crossing count: [`fgw_retained_prefix_length`] clamps the sentinel.
#[inline]
pub fn fgw_length_raw(w: [u32; 4]) -> u32 {
    extract(w[3], 25, 7)
}

/// Whether the word is truncated: `length_raw` is the sentinel (payload §3).
#[inline]
pub fn fgw_truncated(w: [u32; 4]) -> bool {
    fgw_length_raw(w) == FGW_LENGTH_SENTINEL
}

/// Whether the reduced crossing count is valid: only when the word is not truncated, as later cancellations are
/// untracked after the cap (payload §3, §5, §6).
#[inline]
pub fn fgw_reduced_length_valid(w: [u32; 4]) -> bool {
    !fgw_truncated(w)
}

/// The reduced crossing count, the net branch-cut crossings; use only when [`fgw_reduced_length_valid`] (payload §5,
/// §6).
#[inline]
pub fn fgw_reduced_length(w: [u32; 4]) -> u32 {
    fgw_length_raw(w)
}

/// The retained prefix's length: `length_raw`, the sentinel clamped to the capacity; debug and export only, never the
/// reduced crossing count (payload §3, §6; R-86).
#[inline]
pub fn fgw_retained_prefix_length(w: [u32; 4]) -> u32 {
    if fgw_truncated(w) {
        FGW_CAPACITY
    } else {
        fgw_length_raw(w)
    }
}

/// No symbol: one past the last symbol code. [`fgw_symbol`] returns it past the retained prefix, and the append's
/// `prev` holds it after a pop to the empty word (payload §3's `INVALID`).
pub const FGW_NO_SYMBOL: u32 = 4;

/// `payload`: bits 0–24 of the word's `.w`, the top limb of the mixed-radix integer `W` (payload §3).
#[inline]
pub fn fgw_payload(w: [u32; 4]) -> u32 {
    extract(w[3], 0, 25)
}

/// The mixed-radix integer `W` the word packs, as four 32-bit limbs, low first: `x`, `y`, `z`, then `.w`'s `payload`,
/// bits 0–24 (payload §3).
#[inline]
pub fn fgw_mixed_radix(w: [u32; 4]) -> [u32; 4] {
    [w[0], w[1], w[2], extract(w[3], 0, 25)]
}

/// The word holding `W` (four limbs, low first, as [`fgw_mixed_radix`] reads them) and `length`, which the append
/// writes (payload §3).
#[inline]
pub fn fgw_pack(v: [u32; 4], length: u32) -> [u32; 4] {
    [
        v[0],
        v[1],
        v[2],
        insert(insert(0, v[3], 0, 25), length, 25, 7),
    ]
}

/// One limb of [`fgw_div3`]: `r · 2³² + limb`, `r` the remainder carried from the limb above (< 3), divided by 3 over
/// its two 16-bit halves, so no step exceeds a u32 (WGSL has no u64). The quotient limb and the remainder.
#[inline]
pub fn fgw_div3_limb(limb: u32, r: u32) -> (u32, u32) {
    let hi = (r << 16) | (limb >> 16);
    let lo = ((hi % 3) << 16) | (limb & 0xffff);
    (((hi / 3) << 16) | (lo / 3), lo % 3)
}

/// `v` (four limbs, low first) divided by 3, and the remainder: one pop of the base-3 tail, the remainder its digit
/// (payload §3). Long division from the high limb down, by constant indices.
#[inline]
pub fn fgw_div3(v: [u32; 4]) -> ([u32; 4], u32) {
    let (q3, r) = fgw_div3_limb(v[3], 0);
    let (q2, r) = fgw_div3_limb(v[2], r);
    let (q1, r) = fgw_div3_limb(v[1], r);
    let (q0, r) = fgw_div3_limb(v[0], r);
    ([q0, q1, q2, q3], r)
}

/// `perm` composed after digit `e`'s continuation: `x ↦ perm(continuation_symbol(x, e))`, each permutation of the
/// symbol codes packed with code `x`'s image in bits `2x .. 2x + 2` (payload §3's table, read through
/// [`continuation_symbol`]).
#[inline]
pub fn fgw_after(perm: u32, e: u32) -> u32 {
    extract(perm, 2 * continuation_symbol(0, e), 2)
        | (extract(perm, 2 * continuation_symbol(1, e), 2) << 2)
        | (extract(perm, 2 * continuation_symbol(2, e), 2) << 4)
        | (extract(perm, 2 * continuation_symbol(3, e), 2) << 6)
}

/// Symbol `k` of the word's retained prefix, 0-based (`d₀` is symbol 0), or [`FGW_NO_SYMBOL`] at or past its length.
/// Sequential, O(length), never random-access (payload §3): the base-3 tail is popped by depth down to the prefix
/// ending at symbol `k`, then its `k` digits are popped, last first, composing their continuations ([`fgw_after`]),
/// and the composition is applied to the residue, `d₀`. A truncated word's retained prefix is its 76 stored symbols,
/// a debug quantity, not the reduced word (payload §3, §5).
#[inline]
pub fn fgw_symbol(w: [u32; 4], k: u32) -> u32 {
    let length = fgw_retained_prefix_length(w);
    if k >= length {
        return FGW_NO_SYMBOL;
    }
    let mut v = fgw_mixed_radix(w);
    let mut i = k + 1;
    while i < length {
        v = fgw_div3(v).0;
        i += 1;
    }
    let mut perm = 0xe4;
    let mut j = 0;
    while j < k {
        let (q, e) = fgw_div3(v);
        v = q;
        perm = fgw_after(perm, e);
        j += 1;
    }
    extract(perm, 2 * (v[0] & 3), 2)
}

/// Payload §3's frozen `inverse` (symbol codes `a = 0, A = 1, b = 2, B = 3`): part of the binary format.
pub const INVERSE: [u32; 4] = [1, 0, 3, 2];

/// Payload §3's frozen `cont_symbol`: `next = CONT_SYMBOL[digit][prev]`.
pub const CONT_SYMBOL: [[u32; 4]; 3] = [[0, 1, 2, 3], [2, 3, 0, 1], [3, 2, 1, 0]];

/// `predecessor_symbol`, `prev = PREDECESSOR_SYMBOL[digit][next]`: `CONT_SYMBOL` inverted, so equal to it (payload §3).
pub const PREDECESSOR_SYMBOL: [[u32; 4]; 3] = [[0, 1, 2, 3], [2, 3, 0, 1], [3, 2, 1, 0]];

/// `continuation_index`, `digit = CONTINUATION_INDEX[prev][next]`: `CONT_SYMBOL` inverted, and 3 ("invalid") where
/// `next = inverse(prev)` (R-307, payload §3).
pub const CONTINUATION_INDEX: [[u32; 4]; 4] =
    [[0, 3, 1, 2], [3, 0, 2, 1], [1, 2, 0, 3], [2, 1, 3, 0]];

/// The inverse of symbol `s` (payload §3): `INVERSE[s]`, as a comparison chain, not an array index (GPU determinism
/// note § "The discipline", rule 5). `s` is a symbol code, 0…3: `debug_assert!`ed, then masked `& 3` (R-321).
#[inline]
pub const fn inverse(s: u32) -> u32 {
    debug_assert!(s < 4, "s is not a symbol code (R-321)");
    let s = s & 3;
    if s == 0 {
        1
    } else if s == 1 {
        0
    } else if s == 2 {
        3
    } else {
        2
    }
}

/// The symbol digit `e` continues `prev` with (payload §3): `CONT_SYMBOL[e][prev]`, as a comparison chain. `e` is a
/// digit, 0…2: `debug_assert!`ed, then clamped `min(e, 2)` (R-324); `prev` a symbol code, 0…3: `debug_assert!`ed, then
/// masked `& 3` (R-321).
#[inline]
pub fn continuation_symbol(prev: u32, e: u32) -> u32 {
    debug_assert!(prev < 4, "prev is not a symbol code (R-321)");
    debug_assert!(e < 3, "e is not a digit (R-324)");
    let prev = prev & 3;
    let e = e.min(2);
    if e == 0 {
        if prev == 0 {
            0
        } else if prev == 1 {
            1
        } else if prev == 2 {
            2
        } else {
            3
        }
    } else if e == 1 {
        if prev == 0 {
            2
        } else if prev == 1 {
            3
        } else if prev == 2 {
            0
        } else {
            1
        }
    } else if prev == 0 {
        3
    } else if prev == 1 {
        2
    } else if prev == 2 {
        1
    } else {
        0
    }
}

/// The `prev` that digit `e` continued to `next`: the reverse table a cancellation-pop reads (payload §3):
/// `PREDECESSOR_SYMBOL[e][next]`, as a comparison chain. `e` is a digit, 0…2: `debug_assert!`ed, then clamped
/// `min(e, 2)` (R-324); `next` a symbol code, 0…3: `debug_assert!`ed, then masked `& 3` (R-321).
#[inline]
pub fn predecessor_symbol(next: u32, e: u32) -> u32 {
    debug_assert!(next < 4, "next is not a symbol code (R-321)");
    debug_assert!(e < 3, "e is not a digit (R-324)");
    let next = next & 3;
    let e = e.min(2);
    if e == 0 {
        if next == 0 {
            0
        } else if next == 1 {
            1
        } else if next == 2 {
            2
        } else {
            3
        }
    } else if e == 1 {
        if next == 0 {
            2
        } else if next == 1 {
            3
        } else if next == 2 {
            0
        } else {
            1
        }
    } else if next == 0 {
        3
    } else if next == 1 {
        2
    } else if next == 2 {
        1
    } else {
        0
    }
}

/// The digit that continues `prev` with `s`; 3 where `s = inverse(prev)`, which the append never reads (R-307):
/// `CONTINUATION_INDEX[prev][s]`, as a comparison chain. `prev` and `s` are symbol codes, 0…3: each `debug_assert!`ed,
/// then masked `& 3` (R-321), so 3 is returned only in the four inverse cells.
#[inline]
pub const fn continuation_index(prev: u32, s: u32) -> u32 {
    debug_assert!(prev < 4, "prev is not a symbol code (R-321)");
    debug_assert!(s < 4, "s is not a symbol code (R-321)");
    let prev = prev & 3;
    let s = s & 3;
    if prev == 0 {
        if s == 0 {
            0
        } else if s == 1 {
            3
        } else if s == 2 {
            1
        } else {
            2
        }
    } else if prev == 1 {
        if s == 0 {
            3
        } else if s == 1 {
            0
        } else if s == 2 {
            2
        } else {
            1
        }
    } else if prev == 2 {
        if s == 0 {
            1
        } else if s == 1 {
            2
        } else if s == 2 {
            0
        } else {
            3
        }
    } else if s == 0 {
        2
    } else if s == 1 {
        1
    } else if s == 2 {
        3
    } else {
        0
    }
}

/// `simstate_buffer`'s bind group in the fragment (R-343).
pub const SIMSTATE_GROUP: u32 = 1;

/// `simstate_buffer`'s binding number in its group (R-343).
pub const SIMSTATE_BINDING: u32 = 0;

/// `word_buffer`'s bind group in the fragment (R-343).
pub const WORD_GROUP: u32 = 1;

/// `word_buffer`'s binding number in its group (R-343).
pub const WORD_BINDING: u32 = 1;

/// `ic_buffer`'s bind group in the fragment (R-343).
pub const IC_GROUP: u32 = 1;

/// `ic_buffer`'s binding number in its group (R-343).
pub const IC_BINDING: u32 = 2;

/// `quad_buffer`'s bind group in the fragment (R-343).
pub const QUAD_GROUP: u32 = 1;

/// `quad_buffer`'s binding number in its group (R-343).
pub const QUAD_BINDING: u32 = 3;
