//! Generated by `cargo xtask codegen` from the layout table (`crates/ledger/src/payload.rs`); do not edit.
//! The debug catalogue's tests (debug_tooling_plan "Principle"; render contract Part 6), one per view in
//! `crates/render/frag/debug/generated/`: each reads its field from a synthetic sample through the Rust twin of
//! the accessor its view reads it through (REQ-TOOL-017, REQ-TOOL-020), and its negative control stores another
//! value.

use kernel::payload::*;
use validation::negative_control;

/// A synthetic sample: the stored `SimStateFTLE`, its word, its `ICDescriptor` and the read's parameters.
struct Probe {
    s: SimStateFTLE,
    word: [u32; 4],
    ic: ICDescriptor,
    params: ReadParams,
}

/// `altered` when `alter` names `field`, else `value`.
fn pick<T>(alter: Option<&str>, field: &str, value: T, altered: T) -> T {
    if alter == Some(field) {
        altered
    } else {
        value
    }
}

/// Asserts that the field read, `got`, is `want`, failing with `what`.
fn expect<T: PartialEq + std::fmt::Debug>(got: T, want: T, what: &str) {
    assert_eq!(got, want, "{what}");
}

/// The probe: every stored field at its own value, the one `alter` names at another.
fn probe(alter: Option<&str>) -> Probe {
    let mut s = SimStateFTLE::default();
    let mut word = [0u32; 4];
    let mut ic = ICDescriptor::default();
    s.r = pick(
        alter,
        "r",
        [[0.25, 0.28125], [0.3125, 0.34375], [0.375, 0.40625]],
        [[0.5, 0.28125], [0.3125, 0.34375], [0.375, 0.40625]],
    );
    s.p = pick(
        alter,
        "p",
        [[0.5, 0.53125], [0.5625, 0.59375], [0.625, 0.65625]],
        [[0.75, 0.53125], [0.5625, 0.59375], [0.625, 0.65625]],
    );
    s.r_sh = pick(
        alter,
        "r_sh",
        [[0.75, 0.78125], [0.8125, 0.84375], [0.875, 0.90625]],
        [[1.0, 0.78125], [0.8125, 0.84375], [0.875, 0.90625]],
    );
    s.p_sh = pick(
        alter,
        "p_sh",
        [[1.0, 1.03125], [1.0625, 1.09375], [1.125, 1.15625]],
        [[1.25, 1.03125], [1.0625, 1.09375], [1.125, 1.15625]],
    );
    s.S = pick(alter, "S", 1.25, 1.5);
    s.theta = pick(alter, "theta", 1.5, 1.75);
    s.mean_y = pick(alter, "mean_y", 1.75, 2.0);
    s.C_ty = pick(alter, "C_ty", 2.0, 2.25);
    s.E_0 = pick(alter, "E_0", 2.25, 2.5);
    s.Lz_0 = pick(alter, "Lz_0", 2.5, 2.75);
    s.total_substeps = pick(alter, "total_substeps", 2147483648, 2147483649);
    s.closure_min = pick(alter, "closure_min", 3.0, 3.25);
    s.closure_step = pick(alter, "closure_step", 32768, 32769);
    s.packed_a = insert(s.packed_a, pick(alter, "state", 3, 4), 0, 3);
    s.packed_a = insert(s.packed_a, pick(alter, "detail", 2, 3), 3, 2);
    s.packed_a = insert(s.packed_a, pick(alter, "saturated", 1, 0), 5, 1);
    s.packed_a = insert(s.packed_a, pick(alter, "dmin_pair", 1, 2), 6, 2);
    s.packed_a = insert(s.packed_a, pick(alter, "last_symbol", 2, 3), 8, 2);
    s.packed_a = insert(
        s.packed_a,
        u32::from(f32_to_f16_bits(pick(alter, "d_min", 4.75, 5.0))),
        16,
        16,
    );
    s.packed_b = insert(
        s.packed_b,
        u32::from(f32_to_f16_bits(pick(alter, "dE_max", 5.0, 5.25))),
        0,
        16,
    );
    s.packed_b = insert(
        s.packed_b,
        u32::from(f32_to_f16_bits(pick(alter, "dLz_max", 5.25, 5.5))),
        16,
        16,
    );
    s.times = insert(s.times, pick(alter, "t_end_step", 32768, 32769), 0, 16);
    s.times = insert(s.times, pick(alter, "t_dmin_step", 32768, 32769), 16, 16);
    ic.m0 = pick(alter, "m0", 7.25, 7.5);
    ic.m1 = pick(alter, "m1", 7.5, 7.75);
    ic.m2 = pick(alter, "m2", 7.75, 8.0);
    ic.q_mass = pick(alter, "q_mass", 8.0, 8.25);
    ic.rho_mag = pick(alter, "rho_mag", 8.25, 8.5);
    ic.lambda_mag = pick(alter, "lambda_mag", 8.5, 8.75);
    ic.rho_ratio = pick(alter, "rho_ratio", 8.75, 9.0);
    ic.rho_angle = pick(alter, "rho_angle", 9.0, 9.25);
    ic.K_0 = pick(alter, "K_0", 9.25, 9.5);
    ic.V_0 = pick(alter, "V_0", 9.5, 9.75);
    ic.virial_ratio = pick(alter, "virial_ratio", 9.75, 10.0);
    ic.r_min_pair_0 = pick(alter, "r_min_pair_0", 10.0, 10.25);
    word[3] = insert(word[3], pick(alter, "payload", 16777216, 16777217), 0, 25);
    word[3] = insert(word[3], pick(alter, "length", 38, 39), 25, 7);
    let params = ReadParams {
        dt_macro: 0.01,
        delta_0: 1e-6,
        n_renorm: 16,
        horizon_steps: 65535,
    };
    Probe {
        s,
        word,
        ic,
        params,
    }
}

/// `p` through the read side, the Rust twin of the fragment's (lowering Part 3a): its word bound, E = 0, its own
/// masses.
fn read(p: &Probe) -> SimState {
    sim_state_from_ftle(
        &p.s,
        p.word,
        true,
        canonical_nan(),
        false,
        [p.ic.m0, p.ic.m1, p.ic.m2],
        &p.params,
    )
}

/// `r`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_r(p: &Probe) {
    let read = read(p);
    expect(
        read.r,
        [[0.25, 0.28125], [0.3125, 0.34375], [0.375, 0.40625]],
        "`r` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_r() {
    check_r(&probe(None));
}

negative_control!(
    catalogue_view_r,
    "a probe storing another `r` reads another `r`",
    expected = "does not read back the value stored",
    check_r(&probe(Some("r")))
);

/// `p`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_p(p: &Probe) {
    let read = read(p);
    expect(
        read.p,
        [[0.5, 0.53125], [0.5625, 0.59375], [0.625, 0.65625]],
        "`p` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_p() {
    check_p(&probe(None));
}

negative_control!(
    catalogue_view_p,
    "a probe storing another `p` reads another `p`",
    expected = "does not read back the value stored",
    check_p(&probe(Some("p")))
);

/// `r_sh`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_r_sh(p: &Probe) {
    let read = read(p);
    expect(
        read.r_sh,
        [[0.75, 0.78125], [0.8125, 0.84375], [0.875, 0.90625]],
        "`r_sh` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_r_sh() {
    check_r_sh(&probe(None));
}

negative_control!(
    catalogue_view_r_sh,
    "a probe storing another `r_sh` reads another `r_sh`",
    expected = "does not read back the value stored",
    check_r_sh(&probe(Some("r_sh")))
);

/// `p_sh`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_p_sh(p: &Probe) {
    let read = read(p);
    expect(
        read.p_sh,
        [[1.0, 1.03125], [1.0625, 1.09375], [1.125, 1.15625]],
        "`p_sh` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_p_sh() {
    check_p_sh(&probe(None));
}

negative_control!(
    catalogue_view_p_sh,
    "a probe storing another `p_sh` reads another `p_sh`",
    expected = "does not read back the value stored",
    check_p_sh(&probe(Some("p_sh")))
);

/// `S`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_s(p: &Probe) {
    let read = read(p);
    expect(
        read.S.to_bits(),
        1.25_f32.to_bits(),
        "`S` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_s() {
    check_s(&probe(None));
}

negative_control!(
    catalogue_view_s,
    "a probe storing another `S` reads another `S`",
    expected = "does not read back the value stored",
    check_s(&probe(Some("S")))
);

/// `theta`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_theta(p: &Probe) {
    let read = read(p);
    expect(
        read.theta.to_bits(),
        1.5_f32.to_bits(),
        "`theta` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_theta() {
    check_theta(&probe(None));
}

negative_control!(
    catalogue_view_theta,
    "a probe storing another `theta` reads another `theta`",
    expected = "does not read back the value stored",
    check_theta(&probe(Some("theta")))
);

/// `mean_y`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_mean_y(p: &Probe) {
    let read = read(p);
    expect(
        read.mean_y.to_bits(),
        1.75_f32.to_bits(),
        "`mean_y` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_mean_y() {
    check_mean_y(&probe(None));
}

negative_control!(
    catalogue_view_mean_y,
    "a probe storing another `mean_y` reads another `mean_y`",
    expected = "does not read back the value stored",
    check_mean_y(&probe(Some("mean_y")))
);

/// `C_ty`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_c_ty(p: &Probe) {
    let read = read(p);
    expect(
        read.C_ty.to_bits(),
        2.0_f32.to_bits(),
        "`C_ty` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_c_ty() {
    check_c_ty(&probe(None));
}

negative_control!(
    catalogue_view_c_ty,
    "a probe storing another `C_ty` reads another `C_ty`",
    expected = "does not read back the value stored",
    check_c_ty(&probe(Some("C_ty")))
);

/// `E_0`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_e_0(p: &Probe) {
    let read = read(p);
    expect(
        read.E_0.to_bits(),
        2.25_f32.to_bits(),
        "`E_0` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_e_0() {
    check_e_0(&probe(None));
}

negative_control!(
    catalogue_view_e_0,
    "a probe storing another `E_0` reads another `E_0`",
    expected = "does not read back the value stored",
    check_e_0(&probe(Some("E_0")))
);

/// `Lz_0`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_lz_0(p: &Probe) {
    let read = read(p);
    expect(
        read.Lz_0.to_bits(),
        2.5_f32.to_bits(),
        "`Lz_0` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_lz_0() {
    check_lz_0(&probe(None));
}

negative_control!(
    catalogue_view_lz_0,
    "a probe storing another `Lz_0` reads another `Lz_0`",
    expected = "does not read back the value stored",
    check_lz_0(&probe(Some("Lz_0")))
);

/// `total_substeps`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_total_substeps(p: &Probe) {
    let read = read(p);
    expect(
        read.total_substeps,
        2147483648,
        "`total_substeps` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_total_substeps() {
    check_total_substeps(&probe(None));
}

negative_control!(
    catalogue_view_total_substeps,
    "a probe storing another `total_substeps` reads another `total_substeps`",
    expected = "does not read back the value stored",
    check_total_substeps(&probe(Some("total_substeps")))
);

/// `closure_min`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_closure_min(p: &Probe) {
    let read = read(p);
    expect(
        read.closure_min.to_bits(),
        3.0_f32.to_bits(),
        "`closure_min` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_closure_min() {
    check_closure_min(&probe(None));
}

negative_control!(
    catalogue_view_closure_min,
    "a probe storing another `closure_min` reads another `closure_min`",
    expected = "does not read back the value stored",
    check_closure_min(&probe(Some("closure_min")))
);

/// `closure_step`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_closure_step(p: &Probe) {
    let read = read(p);
    expect(
        read.closure_step,
        32768,
        "`closure_step` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_closure_step() {
    check_closure_step(&probe(None));
}

negative_control!(
    catalogue_view_closure_step,
    "a probe storing another `closure_step` reads another `closure_step`",
    expected = "does not read back the value stored",
    check_closure_step(&probe(Some("closure_step")))
);

/// `state`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_state(p: &Probe) {
    let read = read(p);
    expect(read.state, 3, "`state` does not read back the value stored");
}

#[test]
fn catalogue_view_state() {
    check_state(&probe(None));
}

negative_control!(
    catalogue_view_state,
    "a probe storing another `state` reads another `state`",
    expected = "does not read back the value stored",
    check_state(&probe(Some("state")))
);

/// `detail`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_detail(p: &Probe) {
    let read = read(p);
    expect(
        read.detail,
        2,
        "`detail` does not read back the value stored",
    );
    expect(
        read.state,
        3,
        "`detail`'s key `state` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_detail() {
    check_detail(&probe(None));
}

negative_control!(
    catalogue_view_detail,
    "a probe storing another `detail` reads another `detail`",
    expected = "does not read back the value stored",
    check_detail(&probe(Some("detail")))
);

/// `saturated`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_saturated(p: &Probe) {
    let read = read(p);
    expect(
        read.saturated,
        true,
        "`saturated` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_saturated() {
    check_saturated(&probe(None));
}

negative_control!(
    catalogue_view_saturated,
    "a probe storing another `saturated` reads another `saturated`",
    expected = "does not read back the value stored",
    check_saturated(&probe(Some("saturated")))
);

/// `dmin_pair`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_dmin_pair(p: &Probe) {
    let read = read(p);
    expect(
        read.dmin_pair,
        1,
        "`dmin_pair` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_dmin_pair() {
    check_dmin_pair(&probe(None));
}

negative_control!(
    catalogue_view_dmin_pair,
    "a probe storing another `dmin_pair` reads another `dmin_pair`",
    expected = "does not read back the value stored",
    check_dmin_pair(&probe(Some("dmin_pair")))
);

/// `last_symbol`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_last_symbol(p: &Probe) {
    let read = read(p);
    expect(
        read.last_symbol,
        2,
        "`last_symbol` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_last_symbol() {
    check_last_symbol(&probe(None));
}

negative_control!(
    catalogue_view_last_symbol,
    "a probe storing another `last_symbol` reads another `last_symbol`",
    expected = "does not read back the value stored",
    check_last_symbol(&probe(Some("last_symbol")))
);

/// `d_min`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_d_min(p: &Probe) {
    let read = read(p);
    expect(
        read.d_min.to_bits(),
        4.75_f32.to_bits(),
        "`d_min` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_d_min() {
    check_d_min(&probe(None));
}

negative_control!(
    catalogue_view_d_min,
    "a probe storing another `d_min` reads another `d_min`",
    expected = "does not read back the value stored",
    check_d_min(&probe(Some("d_min")))
);

/// `dE_max`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_de_max(p: &Probe) {
    let read = read(p);
    expect(
        read.dE_max.to_bits(),
        5.0_f32.to_bits(),
        "`dE_max` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_de_max() {
    check_de_max(&probe(None));
}

negative_control!(
    catalogue_view_de_max,
    "a probe storing another `dE_max` reads another `dE_max`",
    expected = "does not read back the value stored",
    check_de_max(&probe(Some("dE_max")))
);

/// `dLz_max`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_dlz_max(p: &Probe) {
    let read = read(p);
    expect(
        read.dLz_max.to_bits(),
        5.25_f32.to_bits(),
        "`dLz_max` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_dlz_max() {
    check_dlz_max(&probe(None));
}

negative_control!(
    catalogue_view_dlz_max,
    "a probe storing another `dLz_max` reads another `dLz_max`",
    expected = "does not read back the value stored",
    check_dlz_max(&probe(Some("dLz_max")))
);

/// `t_end_step`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_t_end_step(p: &Probe) {
    let read = read(p);
    expect(
        read.t_end_step,
        32768,
        "`t_end_step` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_t_end_step() {
    check_t_end_step(&probe(None));
}

negative_control!(
    catalogue_view_t_end_step,
    "a probe storing another `t_end_step` reads another `t_end_step`",
    expected = "does not read back the value stored",
    check_t_end_step(&probe(Some("t_end_step")))
);

/// `t_dmin_step`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_t_dmin_step(p: &Probe) {
    let read = read(p);
    expect(
        read.t_dmin_step,
        32768,
        "`t_dmin_step` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_t_dmin_step() {
    check_t_dmin_step(&probe(None));
}

negative_control!(
    catalogue_view_t_dmin_step,
    "a probe storing another `t_dmin_step` reads another `t_dmin_step`",
    expected = "does not read back the value stored",
    check_t_dmin_step(&probe(Some("t_dmin_step")))
);

/// `ftle`, read through the Rust twin of its view's accessor, is the value its derived accessor gives from the unaltered probe.
fn check_ftle(p: &Probe) {
    let read = read(p);
    let reference = probe(None);
    let s = &reference.s;
    let params = &reference.params;
    let n = tm_t_end_step(s.times);
    let ftle_ok = ftle_valid(s.packed_a, true, n, completed_renorms(n, params.n_renorm));
    let delta = benettin_delta(s.r, s.p, s.r_sh, s.p_sh);
    let expected: f32 = ftle(s.S, delta, params.delta_0, n, params.dt_macro, ftle_ok);
    expect(
        read.ftle.to_bits(),
        expected.to_bits(),
        "`ftle` is not its derived accessor's value",
    );
}

#[test]
fn catalogue_view_ftle() {
    check_ftle(&probe(None));
}

negative_control!(
    catalogue_view_ftle,
    "a probe storing another `S` reads another `ftle`",
    expected = "is not its derived accessor's value",
    check_ftle(&probe(Some("S")))
);

/// `energy_drift`, read through the Rust twin of its view's accessor, is the value its derived accessor gives from the unaltered probe.
fn check_energy_drift(p: &Probe) {
    let read = read(p);
    let reference = probe(None);
    let s = &reference.s;
    let masses = [reference.ic.m0, reference.ic.m1, reference.ic.m2];
    let expected: f32 = energy_drift(s.r, s.p, masses, s.E_0);
    expect(
        read.energy_drift.to_bits(),
        expected.to_bits(),
        "`energy_drift` is not its derived accessor's value",
    );
}

#[test]
fn catalogue_view_energy_drift() {
    check_energy_drift(&probe(None));
}

negative_control!(
    catalogue_view_energy_drift,
    "a probe storing another `r` reads another `energy_drift`",
    expected = "is not its derived accessor's value",
    check_energy_drift(&probe(Some("r")))
);

/// `Lz_drift`, read through the Rust twin of its view's accessor, is the value its derived accessor gives from the unaltered probe.
fn check_lz_drift(p: &Probe) {
    let read = read(p);
    let reference = probe(None);
    let s = &reference.s;
    let expected: f32 = Lz_drift(s.r, s.p, s.Lz_0);
    expect(
        read.Lz_drift.to_bits(),
        expected.to_bits(),
        "`Lz_drift` is not its derived accessor's value",
    );
}

#[test]
fn catalogue_view_lz_drift() {
    check_lz_drift(&probe(None));
}

negative_control!(
    catalogue_view_lz_drift,
    "a probe storing another `r` reads another `Lz_drift`",
    expected = "is not its derived accessor's value",
    check_lz_drift(&probe(Some("r")))
);

/// `diffusion`, read through the Rust twin of its view's accessor, is the value its derived accessor gives from the unaltered probe.
fn check_diffusion(p: &Probe) {
    let read = read(p);
    let reference = probe(None);
    let s = &reference.s;
    let params = &reference.params;
    let n = tm_t_end_step(s.times);
    let expected: f32 = diffusion_slope(s.C_ty, n, params.dt_macro);
    expect(
        read.diffusion.to_bits(),
        expected.to_bits(),
        "`diffusion` is not its derived accessor's value",
    );
}

#[test]
fn catalogue_view_diffusion() {
    check_diffusion(&probe(None));
}

negative_control!(
    catalogue_view_diffusion,
    "a probe storing another `C_ty` reads another `diffusion`",
    expected = "is not its derived accessor's value",
    check_diffusion(&probe(Some("C_ty")))
);

/// `n`, read through the Rust twin of its view's accessor, is the value its derived accessor gives from the unaltered probe.
fn check_n(p: &Probe) {
    let read = read(p);
    let reference = probe(None);
    let s = &reference.s;
    let masses = [reference.ic.m0, reference.ic.m1, reference.ic.m2];
    let expected: [f32; 3] = shape(s.r, masses);
    expect(
        read.n.map(f32::to_bits),
        expected.map(f32::to_bits),
        "`n` is not its derived accessor's value",
    );
}

#[test]
fn catalogue_view_n() {
    check_n(&probe(None));
}

negative_control!(
    catalogue_view_n,
    "a probe storing another `r` reads another `n`",
    expected = "is not its derived accessor's value",
    check_n(&probe(Some("r")))
);

/// `m0`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_m0(p: &Probe) {
    let ic = &p.ic;
    expect(
        ic.m0.to_bits(),
        7.25_f32.to_bits(),
        "`m0` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_m0() {
    check_m0(&probe(None));
}

negative_control!(
    catalogue_view_m0,
    "a probe storing another `m0` reads another `m0`",
    expected = "does not read back the value stored",
    check_m0(&probe(Some("m0")))
);

/// `m1`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_m1(p: &Probe) {
    let ic = &p.ic;
    expect(
        ic.m1.to_bits(),
        7.5_f32.to_bits(),
        "`m1` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_m1() {
    check_m1(&probe(None));
}

negative_control!(
    catalogue_view_m1,
    "a probe storing another `m1` reads another `m1`",
    expected = "does not read back the value stored",
    check_m1(&probe(Some("m1")))
);

/// `m2`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_m2(p: &Probe) {
    let ic = &p.ic;
    expect(
        ic.m2.to_bits(),
        7.75_f32.to_bits(),
        "`m2` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_m2() {
    check_m2(&probe(None));
}

negative_control!(
    catalogue_view_m2,
    "a probe storing another `m2` reads another `m2`",
    expected = "does not read back the value stored",
    check_m2(&probe(Some("m2")))
);

/// `q_mass`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_q_mass(p: &Probe) {
    let ic = &p.ic;
    expect(
        ic.q_mass.to_bits(),
        8.0_f32.to_bits(),
        "`q_mass` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_q_mass() {
    check_q_mass(&probe(None));
}

negative_control!(
    catalogue_view_q_mass,
    "a probe storing another `q_mass` reads another `q_mass`",
    expected = "does not read back the value stored",
    check_q_mass(&probe(Some("q_mass")))
);

/// `rho_mag`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_rho_mag(p: &Probe) {
    let ic = &p.ic;
    expect(
        ic.rho_mag.to_bits(),
        8.25_f32.to_bits(),
        "`rho_mag` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_rho_mag() {
    check_rho_mag(&probe(None));
}

negative_control!(
    catalogue_view_rho_mag,
    "a probe storing another `rho_mag` reads another `rho_mag`",
    expected = "does not read back the value stored",
    check_rho_mag(&probe(Some("rho_mag")))
);

/// `lambda_mag`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_lambda_mag(p: &Probe) {
    let ic = &p.ic;
    expect(
        ic.lambda_mag.to_bits(),
        8.5_f32.to_bits(),
        "`lambda_mag` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_lambda_mag() {
    check_lambda_mag(&probe(None));
}

negative_control!(
    catalogue_view_lambda_mag,
    "a probe storing another `lambda_mag` reads another `lambda_mag`",
    expected = "does not read back the value stored",
    check_lambda_mag(&probe(Some("lambda_mag")))
);

/// `rho_ratio`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_rho_ratio(p: &Probe) {
    let ic = &p.ic;
    expect(
        ic.rho_ratio.to_bits(),
        8.75_f32.to_bits(),
        "`rho_ratio` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_rho_ratio() {
    check_rho_ratio(&probe(None));
}

negative_control!(
    catalogue_view_rho_ratio,
    "a probe storing another `rho_ratio` reads another `rho_ratio`",
    expected = "does not read back the value stored",
    check_rho_ratio(&probe(Some("rho_ratio")))
);

/// `rho_angle`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_rho_angle(p: &Probe) {
    let ic = &p.ic;
    expect(
        ic.rho_angle.to_bits(),
        9.0_f32.to_bits(),
        "`rho_angle` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_rho_angle() {
    check_rho_angle(&probe(None));
}

negative_control!(
    catalogue_view_rho_angle,
    "a probe storing another `rho_angle` reads another `rho_angle`",
    expected = "does not read back the value stored",
    check_rho_angle(&probe(Some("rho_angle")))
);

/// `K_0`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_k_0(p: &Probe) {
    let ic = &p.ic;
    expect(
        ic.K_0.to_bits(),
        9.25_f32.to_bits(),
        "`K_0` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_k_0() {
    check_k_0(&probe(None));
}

negative_control!(
    catalogue_view_k_0,
    "a probe storing another `K_0` reads another `K_0`",
    expected = "does not read back the value stored",
    check_k_0(&probe(Some("K_0")))
);

/// `V_0`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_v_0(p: &Probe) {
    let ic = &p.ic;
    expect(
        ic.V_0.to_bits(),
        9.5_f32.to_bits(),
        "`V_0` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_v_0() {
    check_v_0(&probe(None));
}

negative_control!(
    catalogue_view_v_0,
    "a probe storing another `V_0` reads another `V_0`",
    expected = "does not read back the value stored",
    check_v_0(&probe(Some("V_0")))
);

/// `virial_ratio`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_virial_ratio(p: &Probe) {
    let ic = &p.ic;
    expect(
        ic.virial_ratio.to_bits(),
        9.75_f32.to_bits(),
        "`virial_ratio` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_virial_ratio() {
    check_virial_ratio(&probe(None));
}

negative_control!(
    catalogue_view_virial_ratio,
    "a probe storing another `virial_ratio` reads another `virial_ratio`",
    expected = "does not read back the value stored",
    check_virial_ratio(&probe(Some("virial_ratio")))
);

/// `r_min_pair_0`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_r_min_pair_0(p: &Probe) {
    let ic = &p.ic;
    expect(
        ic.r_min_pair_0.to_bits(),
        10.0_f32.to_bits(),
        "`r_min_pair_0` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_r_min_pair_0() {
    check_r_min_pair_0(&probe(None));
}

negative_control!(
    catalogue_view_r_min_pair_0,
    "a probe storing another `r_min_pair_0` reads another `r_min_pair_0`",
    expected = "does not read back the value stored",
    check_r_min_pair_0(&probe(Some("r_min_pair_0")))
);

/// `payload`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_payload(p: &Probe) {
    let read = read(p);
    expect(
        fgw_payload(read.word),
        16777216,
        "`payload` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_payload() {
    check_payload(&probe(None));
}

negative_control!(
    catalogue_view_payload,
    "a probe storing another `payload` reads another `payload`",
    expected = "does not read back the value stored",
    check_payload(&probe(Some("payload")))
);

/// `length`, read through the Rust twin of its view's accessor, is the value the probe stored.
fn check_length(p: &Probe) {
    let read = read(p);
    expect(
        fgw_length_raw(read.word),
        38,
        "`length` does not read back the value stored",
    );
}

#[test]
fn catalogue_view_length() {
    check_length(&probe(None));
}

negative_control!(
    catalogue_view_length,
    "a probe storing another `length` reads another `length`",
    expected = "does not read back the value stored",
    check_length(&probe(Some("length")))
);
